fix(comp:card): remove card footer's padding prop
IDuxFE/idux pull request #1411
Opened 2023-01-13 08:51 UTC by kovsu

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## What is the current behavior?

## What is the new behavior?

## Other information

2023-01-13 09:37 UTC, danranVm requested changes

2023-01-13 09:37 UTC, danranVm commented on packages/components/card/style/index.less
> +    .card-footer-margin(@card-padding-sm);
```suggestion
     .card-size(@card-font-size-sm, @card-padding-sm, 4px 0);
```
这样子就好了，不需要这么复杂

2023-01-13 09:37 UTC, danranVm commented on packages/components/card/style/index.less
> +    height: @height-lg;
```suggestion
```
这个删掉，通过 margin 自动撑开高度，不能写死。

2023-01-13 09:38 UTC, kovsu commented on packages/components/card/style/index.less
> +    .card-footer-margin(@card-padding-sm);
margin bottom 似乎是不需要的吧

2023-01-13 09:40 UTC, danranVm commented
只要掌握了 git rebase 操作，可以不用关 PR， 直接在原来的 PR 上操作就好了。

2023-01-13 09:45 UTC, danranVm commented on packages/components/card/style/index.less
> +    .card-footer-margin(@card-padding-sm);
需要，让整个 footer 的高度撑开一些，看起来更合适一些。

2023-01-13 09:46 UTC, kovsu commented on packages/components/card/style/index.less
> +    .card-footer-margin(@card-padding-sm);
![image](https://user-images.githubusercontent.com/82451257/212289383-0960ed8f-6702-46ec-a650-e48fb539ceb8.png)

但这样看着 我觉得 有点奇怪

2023-01-13 09:51 UTC, danranVm commented on packages/components/card/style/index.less
> +    .card-footer-margin(@card-padding-sm);
额，margin 改成 padding 应该就好了。

2023-01-13 09:55 UTC, kovsu commented on packages/components/card/style/index.less
> +    .card-footer-margin(@card-padding-sm);
![image](https://user-images.githubusercontent.com/82451257/212291192-badd8e35-2679-4204-b95c-b5a82fb42975.png)

刚刚发现有个代码没删掉，这样的话，是不是要把 margi 的值设小一点

2023-01-13 09:57 UTC, kovsu commented on packages/components/card/style/index.less
> +    .card-footer-margin(@card-padding-sm);
![image](https://user-images.githubusercontent.com/82451257/212291667-1bbc807f-14df-4344-9e89-07e8bc902a8f.png)

我是不是要去给这个 button 设置下 waveless

2023-01-16 01:40 UTC, danranVm requested changes

2023-01-16 01:40 UTC, danranVm commented on packages/components/card/src/Card.tsx
>          itemChild = <IxButton {...rest}>{text}</IxButton>
这里不应该直接去修改 item： 不到万不得已，不能去直接修改用户的数据。
改成下面这样就好了

```ts
        const { text, ...rest } = item
        itemChild = <IxButton waveless={true} {...rest}>{text}</IxButton>
```

2023-01-16 07:45 UTC, kovsu commented
为什么我 drop 了之前的 commit 信息，这个 commit 信息，还是存在的啊。我感觉 我又给这个 分支玩坏了。我先关了这个吧，我等下创一个库去学习一下。

2023-01-16 07:45 UTC, closed without merging