fix(comp:select): blur event make span render bad
IDuxFE/idux pull request #1437
Opened 2023-01-25 17:27 UTC by kovsu

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## What is the current behavior?

## What is the new behavior?

## Other information
fix #1431

正常显示：
![image](https://user-images.githubusercontent.com/82451257/214636136-8bb42cb2-01c2-476f-86f7-1423124209d0.png)

错误显示：
![image](https://user-images.githubusercontent.com/82451257/214636397-347d247d-49cb-41ea-8126-5288218a61af.png)

可以发现，错误显示的原因就是没有渲染 ix-selector-item 这个盒子

![image](https://user-images.githubusercontent.com/82451257/214636761-eef0f1b5-e4b6-4ad1-8dfd-729b4c90fa69.png)

错误情况下丢失焦点，inputValue.value 是有的，所以 !inputValue.value 就为 false，导致 item 没有渲染

2023-02-07 02:35 UTC, danranVm requested changes

2023-02-07 02:35 UTC, danranVm commented on packages/components/_private/selector/src/composables/useInputState.ts
> +      props.value[0] = inputValue.value
不能直接去修改用户传入的 props,
这个问题的原因可能是这个改动引起的。https://github.com/IDuxFE/idux/commit/59fc80e5a8439fc34d61ea104f1f53dcce9a701e

看看 1.2 的版本是否存在这个问题呢？

2023-02-07 10:11 UTC, kovsu commented on packages/components/_private/selector/src/composables/useInputState.ts
> +      props.value[0] = inputValue.value
1.2 也有这个问题

2023-02-08 06:10 UTC, danranVm approved these changes

2023-02-08 06:11 UTC, merged