Add `loading` prop for select component
IDuxFE/idux pull request #1439
Opened 2023-02-09 10:34 UTC by kovsu

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## What is the current behavior?

fix #1435

## What is the new behavior?

## Other information

2023-02-13 03:38 UTC, danranVm requested changes

2023-02-13 03:38 UTC, danranVm commented on packages/components/select/src/Select.tsx
> +      const children = [<Panel ref={panelRef} v-slots={slots} {...panelProps.value} loading={props.loading} />]
loading 也应该放到 panelProps 里。

2023-02-13 03:38 UTC, danranVm commented on packages/components/select/demo/Loading.vue
> +}
```suggestion
const dataSource = ref<SelectData[]>([{ label: 'Tom', key: 'tom' }])
const value = ref('tom')
const isLoading = ref(false)

const onLoad = () => {
  if (isLoading.value){
    return 
  }
  isLoading.value = true
  setTimeout(() => {
    isLoading.value = false
    dataSource.value = [{ label: 'Tom', key: 'tom' }, { label: 'Jack', key: 'jack' }, { label: 'Alan', key: 'alan' }]
  }, 3000)
}
```

对于响应式数组，尽可能使用重新赋值的方式去操作数据。

2023-02-13 03:38 UTC, danranVm commented on packages/components/select/src/Select.tsx
> +      if (props.allowInput && inputValue.value) {
记得 rebase 一下。

2023-02-13 03:38 UTC, danranVm commented on packages/components/select/src/panel/Panel.tsx
> +      const loading = props.loading
loading 可以放到上面解构出来

2023-02-13 03:38 UTC, danranVm commented on packages/components/select/src/panel/Panel.tsx
> +      if (loading) {
我更建议是在最后加一个 IxSpin 组件， 而不是在这里。

```
  return <div onMousedown={handlePanelMouseDown}><IxSpin spinning={loading}>{children}</IxSpin></div>
```

2023-02-13 03:38 UTC, danranVm commented on packages/components/select/style/index.less
> +  &-loading {
理论上不需要这个样式。

2023-02-13 08:45 UTC, sallerli1 commented
不建议在面板上加loading，可以加在外部 content 组件上面，面板仅仅是数据展示，耦合太多功能会影响后续扩展问题。

比如以下场景，这样的写法可能没有办法兼容：

1. 用户有自定义面板，loading需要覆盖全部内容
2. loading的时候需要处理浮层内输入的状态，因为可能存在搜索和可输入的情况

2023-02-15 02:22 UTC, danranVm requested changes

2023-02-15 02:22 UTC, danranVm commented on packages/components/select/src/Select.tsx
> +    const handleBlur = () => {
这个地方还是没有正确 rebase 哈，你需要先在 main 分支 pull 一下最新代码，再切换到 select-loading 分支做一次rebase

2023-02-15 02:22 UTC, danranVm commented on packages/components/select/docs/Api.zh.md
> +| `loading` | 是否显示加载中状态 | `boolean \| SpinPublicProps` | `false` | - | - |
这个直接改成 spin 吧， 跟 table 直接保持一致，默认值为 undefined
然后注意下 API 顺序，按照字母顺序排下序

2023-02-15 02:22 UTC, danranVm commented on packages/components/select/src/Select.tsx
> +      }
```suggestion
      const { spin } = props
      const spinProps = isBoolean(spin) ? { spinning: spin } : spin
      return spinProps  ? <IxSpin {...spinProps }>{children}</IxSpin> : children
```

2023-02-15 02:22 UTC, danranVm commented on packages/components/select/src/types.ts
> +import type { SpinPublicProps } from '@idux/components/spin/src/types'
```suggestion
import type { SpinProps } from '@idux/components/spin'
```

2023-02-15 02:22 UTC, danranVm commented on packages/components/select/src/types.ts
> +  loading: { type: [Boolean, Object] as PropType<boolean | SpinPublicProps>, default: false },
```suggestion
  spin: { type: [Boolean, Object] as PropType<boolean | SpinProps >, default: undefined },
```

2023-02-21 11:46 UTC, merged