style(comp:dropdown): add padding to menu within dropdown
IDuxFE/idux pull request #1456
Opened 2023-02-20 06:51 UTC by sallerli1

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## What is the current behavior?
下拉菜单无边距

## What is the new behavior?
为在dropdown中的menu增加padding，padding大小与select一致

## Other information
视觉检视问题

2023-02-20 07:53 UTC, danranVm requested changes

2023-02-20 07:53 UTC, danranVm commented on packages/components/dropdown/style/index.less
> +    padding: @dropdown-menu-container-padding;
padding margin 之类的就不高变量了吧，维护起来太累了。
另外我觉得 8px 是不是太多了，保证 select 那边都该绝有点多了，4px 是不是更合适些。
跟设计师商量下？

2023-02-20 09:11 UTC, sallerli1 commented on packages/components/dropdown/style/index.less
> +    padding: @dropdown-menu-container-padding;
seer的是4px，默认主题的是8，是和select一样的

然后select也是有变量的，就统一了

2023-02-23 08:15 UTC, danranVm approved these changes

2023-02-23 08:16 UTC, merged