fix(cdk:forms): disabled according to status
IDuxFE/idux pull request #1503
Opened 2023-03-16 06:37 UTC by kovsu

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## What is the current behavior?
fix #1502

## What is the new behavior?

## Other information

2023-03-16 12:34 UTC, danranVm requested changes

2023-03-18 06:47 UTC, danranVm requested changes

2023-03-18 06:47 UTC, danranVm commented on packages/cdk/forms/src/models/abstractControl.ts
>            this._disabled.value = this._disabledFn!(this, false)
这行可以删掉了，disable 和 enable 函数内会设置这个值。

2023-03-18 07:18 UTC, kovsu commented on packages/cdk/forms/src/models/abstractControl.ts
>            this._disabled.value = this._disabledFn!(this, false)
啊，我没看到把那行赋值操作给删掉了，我还在钉钉问你了。😂

2023-03-19 04:44 UTC, merged