feat(comp:card): 1.add card comp
IduxFE/idux pull request #163
Opened 2021-01-24 06:36 UTC by CruellyJoHn

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-01-24 06:37 UTC, CruellyJoHn commented
@danranVm @clfeng 麻烦review下

2021-01-24 07:04 UTC, CruellyJoHn commented
@danranVm @clfeng 大佬们先review吧，这个ci出现的问题我留着review出来的问题一起commit

2021-01-24 10:14 UTC, danranVm requested changes
革命尚未成功，加油。

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/src/Card.vue
> +    const hadDefaultSlot = computed(() => hasSlot(slots))
```suggestion
    const hasDefaultSlot = computed(() => hasSlot(slots))
    const hasTitleSlot = computed(() => hasSlot(slots,'title'))
    const hasExtraSlot = computed(() => hasSlot(slots,'extra'))
    const hasFooterSlot = computed(() => hasSlot(slots,'footer'))
```
```

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/src/Card.vue
> +    <ix-spin :spinning="isShowLoading" tip="加载中...">
```suggestion
    <ix-spin :spinning="isShowLoading">
```

不给 tip 吧, 如果要给 tip 也不能直接写死，要用 i18n

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/style/index.less
> +      font-size: @font-size-sm!important;
组件库的样式一般情况下禁止使用 `!importrantl;`

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/style/index.less
> +.ellipsis(){
参考 clearfix.less  把 `ellipsis` 单独抽出去

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/style/index.less
> +@border: @card-border-size solid @card-border-color;
所有定义的变量必须要加 card 前缀

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/style/index.less
> +    box-shadow: 0 1px 2px -2px rgba(0,0,0,.16), 0 3px 6px 0 rgba(0,0,0,.12), 0 5px 12px 4px rgba(0,0,0,.09);
使用 shadow.less 中定义的变量。

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/style/index.less
> +    min-height: 128px;
变量

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/style/index.less
> +    background: #fff;
变量

2021-01-24 10:14 UTC, danranVm commented on packages/components/card/style/index.less
> +      font-size: @font-size-md;
不能直接在组件的less 中使用基础变量，需要定义一个以组件名称开头的变量。

2021-01-24 10:14 UTC, danranVm commented on packages/components/core/config/defaultConfig.ts
> +  loading: false,
loading 去掉。

2021-01-24 10:14 UTC, danranVm commented on packages/components/core/config/types.ts
> +export type CardSize = 'default' | 'small'
size 的类型参考之前的评论

2021-01-28 15:39 UTC, CruellyJoHn commented
@danranVm @clfeng pr问题已修改，麻烦review下

2021-01-29 12:12 UTC, CruellyJoHn commented
@danranVm @clfeng 已经将无用的文件删除了

2021-01-30 14:08 UTC, danranVm requested changes

2021-01-30 14:08 UTC, danranVm commented on packages/components/card/src/Card.vue
> +        <slot v-if="hadDefaultSlot && !loading"></slot>
```suggestion
        <slot />
```
这个插槽感觉没必要有这些判断？

2021-01-30 14:08 UTC, danranVm commented on packages/components/card/src/types.ts
> +  loading: boolean
```suggestion
  hoverable?: boolean
  borderless?: boolean
  loading: boolean
```

2021-01-30 14:08 UTC, danranVm commented on packages/components/core/config/types.ts
> +  loading: boolean
```suggestion
  size: CardSize
  borderless: boolean
  hoverable: boolean
```
你现在这么定义肯定会报错啊？

2021-01-30 14:08 UTC, danranVm commented on packages/components/card/style/index.less
> +@border: @card-border-size solid @card-border-color;
```suggestion
@card-border: @card-border-size @border-style @card-border-color;
```

样式处理还是太糟糕了。

2021-02-20 08:30 UTC, CruellyJoHn commented
@danranVm @clfeng pr问题修复完毕，麻烦review一下

2021-02-20 14:22 UTC, danranVm approved these changes
LGTM.

2021-02-20 14:25 UTC, merged