feat(comp:radio): add radio component
IduxFE/idux pull request #165
Opened 2021-01-26 06:53 UTC by lwh2015

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

add radio component
## What is the new behavior?
add radio component
## Other information

2021-01-26 07:35 UTC, lwh2015 commented
@coolyuantao @danranVm

2021-02-01 06:49 UTC, coolyuantao requested changes

2021-02-01 06:49 UTC, coolyuantao commented on packages/components/radio/src/Radio.vue
> +    <span class="ix-radio-label" @keydown.stop>
有必要加`@keydown.stop` 出于什么考虑？

2021-02-03 09:53 UTC, lwh2015 commented on packages/components/radio/src/Radio.vue
> +    <span class="ix-radio-label" @keydown.stop>
> 有必要加`@keydown.stop` 出于什么考虑？

最开始的考虑是想着这一块是采用`slot`插槽，想着用户在这里可能会绑定自己自定义的点击事件，但又不想触发选中，基于这样子的场景去设想的，但是后来仔细评估后，摒弃了这个想法，然后漏删了这个代码。= =

2021-02-17 03:23 UTC, danranVm requested changes

2021-02-17 03:23 UTC, danranVm commented on packages/components/radio/src/RadioGroup.vue
> +    color: PropTypes.string.def('#00b27a'),
color 这个 props 不要了. 用 class 去控制。

2021-02-17 03:23 UTC, danranVm commented on packages/components/radio/src/RadioGroup.vue
> +    mode: withUndefined(PropTypes.oneOf(['fill', 'border'])).def('border'),
```suggestion
    size:PropTypes.oneOf(['large', 'medium', 'small']).def('medium'),
    mode:PropTypes.oneOf(['fill', 'border']).def('border'),
```

2021-02-17 03:23 UTC, danranVm commented on packages/components/radio/src/RadioGroup.vue
> +        name: 'IxRadioGroup',
这个name 干什么用的？

2021-02-17 03:25 UTC, danranVm requested changes

2021-02-17 03:25 UTC, danranVm commented on packages/components/radio/style/index.less
> +@radio-prefix: ~'@{idux-prefix}-radio';
less 变量定义到 default.less 中去，另外样式部分多参考 antd

2021-02-28 01:10 UTC, lwh2015 commented on packages/components/radio/src/RadioGroup.vue
> +    color: PropTypes.string.def('#00b27a'),
这里是控制按钮单选的颜色，一开始的设计就讨论过，现在怎么不要了？

2021-02-28 01:13 UTC, lwh2015 commented on packages/components/radio/src/RadioGroup.vue
> +        name: 'IxRadioGroup',
设计是判断是否是组的标识

2021-02-28 05:52 UTC, danranVm requested changes

2021-03-02 12:50 UTC, danranVm requested changes

2021-03-02 12:50 UTC, danranVm commented on packages/components/radio/src/radio.ts
> +  const radioGroup = inject(radioGroupKey, {} as RadioGroupConfig)
```suggestion
  const radioGroup = inject(radioGroupToken)
```

2021-03-12 08:20 UTC, lwh2015 commented
@danranVm

2021-03-14 07:46 UTC, danranVm requested changes

2021-03-14 07:46 UTC, danranVm commented on packages/components/radio/src/RadioGroup.vue
> +      }),
```suggestion
      {  props,   change },
```
这样子吧，我感觉更好些。

2021-03-14 07:46 UTC, danranVm commented on packages/components/radio/src/RadioGroup.vue
> +    modelValue: PropTypes.oneOfType([String, Number, Boolean]),
```suggestion
    value: PropTypes.oneOfType([String, Number, Boolean]),
```

2021-03-14 07:46 UTC, danranVm commented on packages/components/radio/src/Radio.vue
> +    @change="isChecked = true"
?

2021-03-17 10:06 UTC, danranVm commented on packages/components/style/default.less
> +@radio-font-size: @font-size-md;
现在 @font-size-md; 是 14px 了，如果你需要 16px 的话，换成 @font-size-lg

2021-03-17 10:06 UTC, danranVm commented on packages/components/radio/index.ts
> +export type { IxRadioComponent, IxRadioButtonComponent, IxRadioGroupComponent } from './src/types'
还需要把 props 的类型导出一下。

2021-03-17 10:06 UTC, danranVm commented on packages/components/radio/src/types.ts
> +export type IxRadioButtonComponent = RadioButtonProps
rebase 一下最新的代码，参考一下其他组件的写法。

2021-03-26 03:47 UTC, lwh2015 commented
@danranVm  look

2021-03-27 14:01 UTC, danranVm approved these changes
LGTM

2021-03-28 11:56 UTC, merged