feat(comp: tooltip): add component tooltip
IduxFE/idux pull request #202
Opened 2021-02-15 05:02 UTC by LaamGinghong

fix #200

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-02-15 08:32 UTC, danranVm requested changes

2021-02-15 08:32 UTC, danranVm commented on packages/components/tooltip/docs/index.zh.md
> +| `visible` | 是否显隐 | `boolean` | - | - | - |
visible 支持一下 v-model 吧

2021-02-15 08:32 UTC, danranVm commented on packages/components/tooltip/src/tooltip.tsx
> +  render() {
在 setup 里返回一个 h 函数代替 render 吧

都不用 tsx, 直接 ts 就行了。

2021-02-16 14:08 UTC, LaamGinghong commented on packages/components/tooltip/docs/index.zh.md
> +| `visible` | 是否显隐 | `boolean` | - | - | - |
这个可以

2021-02-16 14:08 UTC, LaamGinghong commented on packages/components/tooltip/src/tooltip.tsx
> +  render() {
不干，看到渲染函数就头痛，jsx就是为了解决这个问题的，你反其道而行

2021-02-23 13:02 UTC, danranVm commented on packages/components/tooltip/src/tooltip.tsx
> +    const { clsPrefix = 'ix-tooltip' } = attrs
这个是干啥？让用户自定义浮层的 className ? 为什么是 attrs 而不是 props

2021-02-27 10:09 UTC, LaamGinghong commented on packages/components/tooltip/src/tooltip.tsx
> +    const { clsPrefix = 'ix-tooltip' } = attrs
因为这个不是对外暴露的，这个是给popover和popconfirm暴露的

2021-02-27 14:00 UTC, danranVm approved these changes

2021-02-27 14:00 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +    if (immediate ?? state.showDelay === 0) {
这里是为什么？原来的写法是对的啊

2021-02-27 17:33 UTC, LaamGinghong commented on packages/cdk/overlay/src/useOverlay.ts
> +    if (immediate ?? state.showDelay === 0) {
改不改逻辑都是一样的，但是用 `??` 更符合语义，`immediate`的优先级高于 `state.showDelay`

2021-02-28 02:54 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +    if (immediate ?? state.showDelay === 0) {
这里看着就很奇怪，建议改成：
```ts
const show = (immediate = false): void => {
    _clearTimer()
    if (immediate || state.showDelay === 0) {
```

2021-03-01 06:14 UTC, merged