feat(comp:timeline): add timeline component
IduxFE/idux pull request #204
Opened 2021-02-15 09:48 UTC by sjia0307

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

add timeline component
## What is the new behavior?
add timeline component
## Other information

2021-02-17 03:03 UTC, danranVm requested changes

2021-02-17 03:03 UTC, danranVm commented on packages/components/timeline/src/TimelineItem.vue
> +    color: PropTypes.string.def('#1890ff'),
所有的颜色都需要从less 变量中获取。
```less
@preset-colors: red, orange, gold, yellow, canary, prasinous, verdant, green, cyan, sky, blue, admiral, purple, magenta,
  lime, grey;
```
建议：每个颜色对应一个 class 名字，然后添加对应的 class,  如果不存在的话，再直接设置 style

```less
    // mixin to iterate over colors and create CSS class for each one
    .make-color-classes(@i: length(@preset-colors)) when (@i > 0) {
      .make-color-classes(@i - 1);
      @color: extract(@preset-colors, @i);
      &-@{color} {
        background: @@color;
      }
    }
    .make-color-classes();
```

2021-02-17 03:03 UTC, danranVm commented on packages/components/timeline/style/index.less
> +    &__dot {
class 命名统一用 `-` 分割，参考 antd 的 class 命名

2021-02-18 03:52 UTC, sjia0307 commented on packages/components/timeline/docs/index.zh.md
> +| `mode` | 时间轴和内容的相对位置 | `left\|alternate \|right` | `right` | - |- |
这里还是保留mode和position感觉好点，mode是排列模式，position是具体的方向。我把TimelineItemMode改为TimelineItemPosition

2021-02-18 03:57 UTC, sjia0307 commented on packages/components/timeline/src/types.ts
> +export type TimelineProps = Readonly<TimelineOriginalProps>
这里是Readonly，不是Partial

2021-02-19 02:30 UTC, danranVm requested changes

2021-02-19 02:30 UTC, danranVm commented on packages/components/core/utils/colors.ts
> +export const isPresetColor = (color?: string): boolean => {
```suggestion
export const isPresetColor = (color: string | undefined): boolean => {
```

? 和显式的声明为 undefined 是有区别的, 这里显式声明更符合使用场景
- ? 表示可以不传
- undefined 表示必传，但是可以为 undefined

2021-02-19 02:30 UTC, danranVm commented on packages/components/timeline/demo/Reverse.vue
> +<script lang="ts">
文档里这些没用的初始模板删掉吧，
另外 Demo 也需要注意下，参考下其他组件或者 antd 的 Demo ，完善一下。

2021-02-19 02:30 UTC, danranVm commented on packages/components/timeline/docs/index.zh.md
> +| `mode` | 时间轴和内容的相对位置 | `left\|alternate \|right` | `right` | - |- |
@Pupils-web 你的意见呢？

2021-02-19 02:30 UTC, danranVm commented on packages/components/timeline/src/Timeline.vue
> +        class: useClasses(itemPositionArr),
```html
<ix-timeline class='custom-class' />
```

这种情况  `custom-class` 会被保留吗？

2021-02-19 02:30 UTC, danranVm commented on packages/components/timeline/src/TimelineItem.vue
> +  const { props, slots } = getCurrentInstance()!
我这里是建议把 props 和 slots 当参数传进来，这样不会丢失类型

2021-02-19 02:30 UTC, danranVm commented on packages/components/timeline/src/TimelineItem.vue
> +  const { props } = getCurrentInstance()!
同上

2021-02-19 02:30 UTC, danranVm commented on packages/components/timeline/src/TimelineItem.vue
> +      'border-color': props.color,
这里是不是换成 background 好点？ less 里也是。

2021-02-19 03:49 UTC, sjia0307 commented on packages/components/timeline/src/TimelineItem.vue
> +      'border-color': props.color,
轴点的样式是一个圆环，所以不能用background；其次pendingDot支持传一个字符串，或者通过插槽传一个icon，color会作用在其上面

2021-02-19 03:50 UTC, sjia0307 commented on packages/components/timeline/src/Timeline.vue
> +        class: useClasses(itemPositionArr),
会被保留

2021-02-20 05:07 UTC, sjia0307 commented on packages/components/timeline/src/TimelineItem.vue
> +  const { props, slots } = getCurrentInstance()!
Timeline.vue我也一起改了

2021-02-20 13:34 UTC, Pupils-web commented on packages/components/timeline/docs/index.zh.md
> +| `mode` | 时间轴和内容的相对位置 | `left\|alternate \|right` | `right` | - |- |
我建议是用`position` 因为其实这里不管是`mode`和`position`都没办法完美表达你这个相对位置的概念，那就从使用习惯上来吧，子组件是`position`，父组件也用`position`吧，多少还有个位置的意思在这里

2021-02-21 08:18 UTC, danranVm approved these changes
LGTM.

2021-02-21 08:18 UTC, merged