feat(cdk: overlay): add global click event
IduxFE/idux pull request #207
Opened 2021-02-16 14:59 UTC by LaamGinghong

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-02-16 15:00 UTC, LaamGinghong commented
cdk增加全局点击事件，之前当浮层的trigger是click的时候，只有重新点slot才会关闭浮层，现在增加点击全局也能关闭浮层，增加交互体验

2021-02-16 15:00 UTC, LaamGinghong commented
@danranVm 请review

2021-02-17 09:53 UTC, LaamGinghong commented
@danranVm 有空看看

2021-02-17 14:09 UTC, danranVm requested changes

2021-02-17 14:09 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +      if (fn === oldFn) {
你现在这种写法，这里永远都不可能相等。

2021-02-17 14:09 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +    beforeUnmount(el) {
```suggestion
    unmounted(el) {
```

所有的资源释放操作统一放到 unmounted 中

2021-02-17 14:09 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +export default useClickOutside()
```suggestion
export default ClickOutside
```

2021-02-17 14:09 UTC, danranVm commented on packages/cdk/utils/__tests__/wait.spec.ts
> +    expect(mid - begin).toBeGreaterThanOrEqual(10)
这里 test 没跑通过

2021-02-17 14:09 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +    await wait(state.showDelay)
这里的理由是什么？你这有点过分。。。

2021-02-17 14:12 UTC, LaamGinghong commented on packages/cdk/click-outside/src/useClickOutside.ts
> +type SelfMap = WeakMap<HTMLElement, (e: MouseEvent) => void>
我这样定义是为了文档方便👀

2021-02-17 14:13 UTC, LaamGinghong commented on packages/cdk/click-outside/src/useClickOutside.ts
> +      }
我觉得我那种写法还挺优雅的🐶

2021-02-17 14:14 UTC, LaamGinghong commented on packages/cdk/click-outside/src/useClickOutside.ts
> +      if (fn === oldFn) {
如果是因为别的原因导致update，这里会不会相等？

2021-02-17 14:15 UTC, LaamGinghong commented on packages/cdk/overlay/src/useOverlay.ts
> +    await wait(state.showDelay)
因为有了showDelay，所以后面的overlayRef还没有拿到值，但是跑了createPopper，所以需要有个延时，等一下让组件渲染出来

2021-02-17 14:17 UTC, LaamGinghong commented on packages/cdk/utils/__tests__/wait.spec.ts
> +    expect(mid - begin).toBeGreaterThanOrEqual(10)
这个有点难跑，因为延时不是固定的，你有什么建议该这里的用例

2021-02-17 14:18 UTC, LaamGinghong commented on packages/cdk/click-outside/src/useClickOutside.ts
> +export default useClickOutside()
这是啥套路，我是用闭包导出返回值啊

2021-02-17 14:19 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +type SelfMap = WeakMap<HTMLElement, (e: MouseEvent) => void>
文档也直接用 `() => void` 表示就好了。

2021-02-17 14:20 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +      }
优雅你个头，有 bug.

2021-02-17 14:20 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +      if (fn === oldFn) {
你的 fn 永远是一个新的引用 怎么可能相等。

2021-02-17 14:21 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +export default useClickOutside()
我的意思是改成对象形式的指令，就这样 export 就好了。

2021-02-17 14:22 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +    await wait(state.showDelay)
install 的时候能否跳过 showDelay

2021-02-17 14:22 UTC, danranVm commented on packages/cdk/utils/__tests__/wait.spec.ts
> +    expect(mid - begin).toBeGreaterThanOrEqual(10)
我感觉就不应该搞一个这个函数。。

2021-02-27 07:50 UTC, danranVm approved these changes
lgtm

2021-02-27 07:50 UTC, merged