feat(comp: statistic): add statistic component
IduxFE/idux pull request #208
Opened 2021-02-19 15:21 UTC by clfeng

fix #95

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

dont hava statistic compoenent
## What is the new behavior?
have the statistic compoenent
## Other information

2021-02-20 15:14 UTC, danranVm requested changes

2021-02-20 15:14 UTC, danranVm commented on packages/components/statistic/src/Statistic.vue
> +    return formatNum(props.value, precision)
formatNum 是不是实现的有点复杂了, 考虑简化一下？

```ts
  private formatNumber(value, precision) {
    // TODO: i18n support 
    const decimalSeparator =  '.' 
    const [int, decimal] = String(value).split(decimalSeparator);
    const _decimal = decimal ? `${decimalSeparator}${decimal}` :  ''
    return { int, decimal: _decimal.slice(0, precision).padEnd(precision, '0') }
  }
```

`slice(0, precision).padEnd(precision, '0')` 这句代码看看有没有更好的方式。

2021-02-20 15:14 UTC, danranVm commented on packages/components/statistic/src/Statistic.vue
> +  computed: {
不要用这种 Options API, 直接在 template 写就好了，或者 在 setup 里 computed

2021-02-20 15:14 UTC, danranVm commented on packages/components/statistic/style/index.less
> +  font-size: 14px;
这些可以数值类的样式，能不写死的都不要写死，参考其他组件的写法，在 default.less 里定义好变量。

2021-02-21 03:06 UTC, clfeng commented on packages/components/statistic/demo/Unit.vue
> +    /deep/ .ix-statistic-content {
因为上面加了scoped，如果不加样式不会生效

2021-02-21 03:19 UTC, clfeng commented on packages/components/statistic/src/Statistic.vue
> +    return formatNum(props.value, precision)
这个不可以这么实现，要考虑用户的输入不合法的情况，可以看下相应的备注；这里稍微修改下相应的命名

2021-02-21 03:58 UTC, danranVm commented on packages/components/statistic/src/Statistic.vue
> +    return formatNum(props.value, precision)
```suggestion
const useFormat = (props: StatisticProps, config: StatisticConfig) => {
  return computed(() => {
    const formatter = props.formatter || config. formatter
    const precision = props.precision || config.precision
    return formatter(props.value, precision)
```

这样设计或许更好一些？

2021-02-21 06:55 UTC, Usualminds commented on packages/components/statistic/src/Statistic.vue
> +            <span class="ix-statistic-content-value-int">{{ formatedValue.valueInt || formatedValue.value }}</span>
涉及数值展示类型的，建议考虑一下数值超长位数的科学计数法，参见 [科学计数法](https://zh.wikipedia.org/wiki/%E7%A7%91%E5%AD%A6%E8%AE%B0%E6%95%B0%E6%B3%95)

2021-02-21 08:06 UTC, clfeng commented on packages/components/statistic/src/Statistic.vue
> +            <span class="ix-statistic-content-value-int">{{ formatedValue.valueInt || formatedValue.value }}</span>
这个不做过多考虑，因为提供了插槽以及formatter函数接口给用户，如果用户需要的话，可以自定义实现；

2021-02-21 10:41 UTC, danranVm requested changes

2021-02-21 10:41 UTC, danranVm commented on packages/components/statistic/src/statistic.ts
> +export const statisticInjectionKey: InjectionKey<StatisticProps> = Symbol()
这个是用来干嘛的？没看到有地方使用啊

2021-02-21 10:41 UTC, danranVm commented on packages/components/statistic/src/Statistic.vue
> +            .{{ formatedValue.decimal }}
```suggestion
            {{ formatedValue.decimal }}
```
在format 的时候，就把分隔符包含在 decimal 内。便于用户更好的自定义，
另外，我看 ng 的代码里，国际化处理的时候，分隔符不一定是小数点，我们后续增加国际化需求的时候也可能需要考虑。

2021-02-21 10:41 UTC, danranVm commented on packages/components/core/config/types.ts
> +}
```suggestion
export interface NumberFormatted {
   /** 格式化后的值 */
   value: string
   /** 格式化后的整数部分 */
   int?: string
    /** 格式化后的小数部分 */
   decimal?: string
}
export type NumberFormatter = (value: string | number, precision: number) => NumberFormatted
export interface StatisticConfig {
  precision: number
  formatter: NumberFormatter
}
```

2021-02-21 10:41 UTC, danranVm commented on packages/components/core/config/format.ts
> +}
```suggestion
export const numberFormatter: NumberFormatter = (value: string | number, precision: number) => {
  const numReg = /^(\d+)(\.(\d+))?$/
  const numMatchRet = String(value).match(numReg)

  if (!numMatchRet) {
    return { value: String(value) }
  } else {
    const [int, separator, _decimal = ''] = numMatchRet
    let decimal = _decimal.slice(0, precision).padEnd(precision, '0')
    decimal =  decimal.length > 0 ? `${separator}${decimal}` : ''

    return {
      value: decimal.length > 0 ? `${int}${decimal}` : int,
      int,
      decimal,
    }
  }
}
```

这个文件的名字也改成 numberFormatter 吧

2021-02-21 14:41 UTC, danranVm approved these changes

2021-02-21 14:46 UTC, danranVm commented on packages/components/statistic/src/Statistic.vue
> +            <span class="ix-statistic-content-value-int">{{ formatedValue.valueInt || formatedValue.value }}</span>
用户高级的自定义需求，可以通过 formatter 或者 slot 去实现。

2021-02-22 02:05 UTC, Usualminds commented on packages/components/statistic/src/Statistic.vue
> +            <span class="ix-statistic-content-value-int">{{ formatedValue.valueInt || formatedValue.value }}</span>
OK

2021-02-22 02:07 UTC, Usualminds approved these changes
@danranVm @clfeng 我这边没什么问题了

2021-02-22 02:08 UTC, danranVm commented
LGTM.

2021-02-22 02:08 UTC, merged