feat(comp: affix): add affix component
IduxFE/idux pull request #209
Opened 2021-02-21 04:10 UTC by jackson-yyy

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

don't have a affix component

## What is the new behavior?
have a affix component

## Other information

2021-02-21 09:33 UTC, danranVm requested changes
可以多参考一下 backtop 组件

2021-02-21 09:33 UTC, danranVm commented on packages/components/affix/src/Affix.vue
> +  </div>
```suggestion
  <div ref="affixRef" :style="affixStyle" class="ix-affix">
    <div ref="contentRef" class="ix-affix-content" :style="contentStyle">
      <slot></slot>
    </div>
  </div>
```

最外层的 class 名和组件同名，整体组件都保持这个风格吧。

2021-02-21 09:33 UTC, danranVm commented on packages/components/affix/src/Affix.vue
> +    })
```suggestion
    const offset = computed(() => {
      const _offset = props.offset
      if(isObject(_offset)){
        return _offset
      }
      return { top: toNumber(_offset) }
    })
```

2021-02-21 09:33 UTC, danranVm commented on packages/components/affix/src/Affix.vue
> +    const isWindow = computed(() => !isHTMLElement(container.value))
这个就不要了吧，在用的时候判断一下就好了 `container === window`

2021-02-21 09:33 UTC, danranVm commented on packages/components/affix/src/Affix.vue
> +    container: PropTypes.oneOfType([PropTypes.string, HTMLElement, Window]).def(() => window),
```suggestion
    target: withUndefined(PropTypes.oneOfType([PropTypes.string, HTMLElement])),
```
跟 backtop 保持一致吧

2021-02-21 09:33 UTC, danranVm commented on packages/components/affix/src/Affix.vue
> +      },
```suggestion
      (currTarget, prevTarger) => {
        removeListeners(prevTarger)
        initContainer()
        measure()
      },
```

2021-02-22 08:33 UTC, Pupils-web reviewed
已审

2021-02-24 01:48 UTC, danranVm requested changes

2021-02-24 01:48 UTC, danranVm commented on packages/components/affix/demo/Basic.vue
> +/deep/.ix-affix {
```suggestion
:deep(.ix-affix) {
```

2021-02-24 01:48 UTC, danranVm commented on packages/components/affix/src/utils.ts
> +const DIRECTION: Direction[] = ['top', 'bottom', 'left', 'right']
```suggestion
const eventList = ['scroll', 'resize']
const directions: Direction[] = ['top', 'bottom', 'left', 'right']
```
只有跨模块使用的常量才需要全大写命名

2021-02-24 01:48 UTC, danranVm commented on packages/components/affix/src/utils.ts
> +  ;(Object.getOwnPropertyNames(offset) as Direction[]).forEach(dire => {
```suggestion
  Object.keys(offset).forEach(dire => {
```

2021-02-24 01:48 UTC, danranVm commented on packages/components/affix/__tests__/util.spec.ts
> +import { getTargetSize, getContainer, rafFn } from '../src/utils'
组件内部的 utils 可以不需要单元测试的，按理说你在测试组件的时候，这些场景都会跑到。

2021-02-24 01:48 UTC, danranVm commented on packages/components/affix/src/Affix.vue
> +    throttleTime: PropTypes.number,
这玩意不是说移除了吗。还有文档也记得删一下。

2021-02-24 01:48 UTC, danranVm commented on packages/components/core/utils/propsHandler.ts
> +}
```suggestion
const getTarget = (target: HTMLElement | string | undefined) => {
  if (isHTMLElement(target)) {
    return target
  }
  if (isString(target)) {
    const container = document.querySelector<HTMLElement>(target)
    if (container) {
      return container
    } else {
      Logger.warn(`target does not exist: ${target}, default value are already used: window.`)
    }
  }
  return window
}
```

cdk 里的那个删掉吧，另外记得在 core/utils/index.ts 里 export 一下。

2021-02-24 01:48 UTC, danranVm commented on packages/components/back-top/src/BackTop.vue
> +import { getTarget } from '@idux/components/core/utils/propsHandler'
```suggestion
import { getTarget } from '@idux/components/core/utils'
```

跟上面的 easeInOutQuad  合到一起吧

2021-02-24 01:48 UTC, danranVm commented on packages/components/affix/src/Affix.vue
> +import { getTarget } from '@idux/components/core/utils/propsHandler'
```suggestion
import { getTarget } from '@idux/components/core/utils'
```

2021-02-24 15:25 UTC, danranVm approved these changes
LGTM.

2021-02-24 15:28 UTC, merged