WIP: feat(comp:grid): add basic grid
IduxFE/idux pull request #220
Opened 2021-02-27 09:52 UTC by zymoplastic

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-02-27 13:07 UTC, danranVm requested changes

2021-02-27 13:07 UTC, danranVm commented on packages/components/grid/src/Col.vue
> +      const verticalGutter = gutter.value[1]
```suggestion
    if (gutter) {
      const[horizontalGutter, verticalGutter] = gutter.value
```

2021-02-27 13:07 UTC, danranVm commented on packages/components/grid/src/Col.vue
> +        style.paddingLeft = `${getPaddingNum(horizontalGutter)}px`
```suggestion
        style.paddingLeft = `${horizontalGutter / 2 }px`
```
更直观，我刚刚找 `getPaddingNum` 找了半天。。。

2021-02-27 13:18 UTC, zymoplastic commented on packages/components/core/config/defaultConfig.ts
> +  RowConfig,
这里还有一个 Col, 后面如果 Col 有全局配置就不好命名了

2021-02-27 13:21 UTC, zymoplastic commented on packages/components/grid/docs/index.zh.md
> +| `wrap`    | 是否自动换行                                                 | `boolean`             | true    | ✅        | -    |
加一个配置好些吧? 我感觉确实有 no-wrap 的需求, 比如仪表盘某一行的内容是不能换行的

2021-02-27 13:28 UTC, danranVm commented on packages/components/core/config/defaultConfig.ts
> +  RowConfig,
如果有的话，就全放在 gridConfig 吧。

2021-02-27 14:01 UTC, zymoplastic commented on packages/components/grid/src/Row.vue
> +    const classNamePrefix = 'ix'
我这里只是预留, 猜测后面全局可以配置 prefix, 那我这里删一下

2021-03-09 09:36 UTC, zymoplastic commented
@danranVm 麻烦 review 一下

2021-03-09 15:20 UTC, danranVm approved these changes
其他的没什么问题了。

2021-03-09 15:20 UTC, danranVm commented on packages/cdk/breakpoint/src/breakpoints.ts
> +import invert from 'lodash/invert'
```ts
import invert from 'lodash/invert'

type KeyFromValue<V, T extends Record<PropertyKey, PropertyKey>> = {
  [K in keyof T]: V extends T[K] ? K : never
}[keyof T]

type Invert<T extends Record<PropertyKey, PropertyKey>> = {
  [V in T[keyof T]]: KeyFromValue<V, T>
}

export const BreakpointKeys = ['xs', 'sm', 'md', 'lg', 'xl'] as const

export const Breakpoints = {
  xs: '(max-width: 767.99px)',
  sm: '(min-width: 768px) and (max-width: 1023.99px)',
  md: '(min-width: 1024px) and (max-width: 1279.99px)',
  lg: '(min-width: 1280px) and (max-width: 1719.99px)',
  xl: '(min-width: 1720px)',
} as const

export type BreakpointKey = keyof typeof Breakpoints

export type ScreenMap = Partial<Record<BreakpointKey, boolean>>

// { '(max-width: 767.99px)': 'xs' }
const mediaScreenMap = invert(Breakpoints) as Invert<typeof Breakpoints>

/** { '(min-width: 768px) and (max-width: 1023.99px)': true } => { sm: true } */
export const convertMediaToScreen = (medias: Record<keyof typeof mediaScreenMap, boolean>): ScreenMap => {
  const result: ScreenMap = {}
  const keys = Object.keys(medias) as Array<keyof typeof mediaScreenMap>
  keys.forEach(media => (result[mediaScreenMap[media]] = medias[media]))
  return result
}
```

在你的基础上改了一版，你看看？`ScreenMap` 的命名还是不满意，但是也想不到更好的。

2021-03-10 01:33 UTC, zymoplastic commented on packages/cdk/breakpoint/src/breakpoints.ts
> +import invert from 'lodash/invert'
这样可以的, 名字我再看看能不能优化下

2021-03-10 02:20 UTC, danranVm commented on packages/components/grid/src/col.ts
> +    }
```suggestion
  const sizeValue = props[size]
  if(isUndefined(attr)){
    allBreakpointCls = {
      ...allBreakpointCls,
      ...getSingleSizeCls(colCls, size, normalizeSizeProps(sizeValue)),
    }
  }
```

2021-03-10 08:13 UTC, merged