feat(comp:message): add message component (#36)
IduxFE/idux pull request #237
Opened 2021-03-11 14:32 UTC by manchixue

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-03-11 14:35 UTC, manchixue commented
message的全局配置通过useGlobalConfig暂时是不能生效的。message是单独创建的实例，所以后续需要提个issue修改下useGlobalConfig进行解决？

2021-03-12 02:15 UTC, danranVm requested changes

2021-03-12 02:15 UTC, danranVm commented on packages/components/message/src/Message.comp.tsx
> +        <div class="ix-message-item__content">
```suggestion
        <div class="ix-message-item-content">
```
class 命名不使用 下划线，统一使用中划线。

2021-03-12 02:15 UTC, danranVm commented on packages/components/message/src/Message.comp.tsx
> +    type: PropTypes.oneOfType([PropTypes.oneOf(['success', 'error', 'info', 'warn'] as const), PropTypes.string]).def(
```suggestion
    type: PropTypes.oneOf(['success', 'error', 'info', 'warn'] as const),
```
没必要支持 string 吧，好像没意义。

2021-03-12 02:15 UTC, danranVm commented on packages/components/message/src/message.service.tsx
> +    duration?: number,
```suggestion
   content: string | VNode, options?: Partial<Omit<MessageListItem, 'type'>>
```

之前不是讨论过，用 ng-zorro 的那种 API 么。。。

2021-03-12 02:15 UTC, danranVm commented on packages/components/message/style/index.less
> +@message-item-content-max-width: 480px;
这些变量提取到 default.less 中去。注意，margin, line-height ，font-size 之类的要使用现有的变量，参考一下其他组件。

2021-03-12 06:29 UTC, danranVm requested changes

2021-03-12 06:29 UTC, danranVm commented on packages/components/icon/src/icons.ts
> +import { ExclamationCircleFilled } from '../definitions'
```suggestion
import { ExclamationCircleFilled } from '../definitions/exclamationCircleFilled '
```

2021-03-12 06:29 UTC, danranVm commented on packages/components/message/__tests__/message.spec.ts
> +import { MessageService } from '../index'
```suggestion
import MessageService from '../src/message.service'
```

2021-03-12 06:29 UTC, danranVm commented on packages/components/message/src/Message.comp.tsx
> +import IxIcon from '@idux/components/icon/src/Icon.vue'
```suggestion
import { IxIcon } from '@idux/components/icon'
```

2021-03-12 06:29 UTC, danranVm commented on packages/components/message/src/Message.comp.tsx
> +import { MessageItemProps, useGlobalConfig } from '@idux/components'
```suggestion
import { useGlobalConfig } from '@idux/components/core/config'
```

2021-03-12 06:29 UTC, danranVm commented on packages/components/message/src/Message.comp.tsx
> +import { MessageType } from './types'
```suggestion
import { MessageItemProps, MessageType } from './types'
```

2021-03-12 06:29 UTC, danranVm commented on packages/components/message/src/message.service.tsx
> +import { useContainer } from '@idux/cdk/portal/src/useContainer'
```suggestion
import { useContainer } from '@idux/cdk/portal'
```
另外这个文件名改成 messageService.tsx

2021-03-12 06:29 UTC, danranVm commented on packages/components/message/src/message.service.tsx
> +import IxPortal from '@idux/cdk/portal/src/Portal.vue'
```suggestion
import { IxPortal } from '@idux/cdk/portal'
```

2021-03-12 06:29 UTC, danranVm commented on packages/components/message/src/Message.comp.tsx
> +import { defineComponent, onBeforeUnmount, onMounted, SetupContext, isVNode, h, computed } from 'vue'
这个文件名改成 message.tsx

2021-03-13 10:22 UTC, manchixue commented on packages/components/message/src/message.service.tsx
> +    duration?: number,
api是参考的ng-zorro的

2021-03-13 10:25 UTC, manchixue commented on packages/components/message/src/Message.comp.tsx
> +function usePauseOnHover(options: { duration: number; pauseOnHover: boolean }) {
主要是想将相关逻辑抽成到函数内处理。避免setup函数内容过多

2021-03-13 13:34 UTC, manchixue commented
review问题已修改 @danranVm 辛苦有空再看看

2021-03-13 14:25 UTC, danranVm approved these changes
LGTM

2021-03-13 14:27 UTC, merged