feat(comp: progress): add component progress(#35)
IduxFE/idux pull request #240
Opened 2021-03-12 08:25 UTC by hangboss1761

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-03-12 10:05 UTC, danranVm requested changes

2021-03-13 04:46 UTC, danranVm requested changes

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/useCommonLogic.ts
> +}
```suggestion
export function useStatusClass(
  status: ComputedRef<ProgressStatus>,
): ComputedRef<string> {
  const prefix = 'ix-progress'
  const statusClassMap: Record<ProgressStatus, string> = {
    normal: `${prefix}-status-normal`,
    exception: `${prefix}-status-exception`,
    success: `${prefix}-status-success`,
    active: `${prefix}-status-active`,
  } 
  return computed(() => statusClassMap[status.value])
}
```

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/types.ts
> +  success?: ProgressSuccess
感觉这个 success 还是拆成两个 props 比较好？`successPercent` `successStrokeColor`

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/useCommonLogic.ts
> +}
```suggestion
export function useProgressStatus(props: ProgressProps): ComputedRef<ProgressStatus> {
  return computed(() => {
    const percent = convertPercent(props.percent)
    const successPercent = convertPercent(props.success?.percent)
    const statusArray: ProgressStatus[] = ['normal', 'success', 'exception', 'active']
    if (
      ! statusArray.includes(props.status) &&
      (percent >= 100 || successPercent >= 100)
    ) {
      return 'success'
    } else {
      return props.status || 'normal'
    }
  })
}
```

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/useCommonLogic.ts
> +  const progressFormatFn = props.format || (percent => percent + '%')
format 支持一下 全局配置？ 默认为 `(percent => percent + '%')`

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/useCommonLogic.ts
> +      (progressStatus.value === 'normal' && convertPercent(props.percent) === 100),
100 定义成一个常量吧，把用到的地方都替换一下。

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/useCommonLogic.ts
> +}
```suggestion
export function useSmallSize(props: ProgressProps, config: ProgressConfig): ComputedRef<boolean> {
  return computed(() =>{
    const size = props.size ?? config.size
    return size === 'small' 
  }
}
```

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/Progress.vue
> +  <component :is="tag" v-bind="$props" class="ix-progress">
```suggestion
  <component :is="tag" v-bind="$props" : percent="percent" : successPercent="successPercent"  class="ix-progress">
```
可以在父组件把参数都格式化好，然后在子组件内部使用的时候，就不用在考虑数据一致性了。
相应的 convertPercent 都可以干掉。

如果还有其他需要处理的参数也可以放在父组件。

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/Line.vue
> +    })
这两个直接合成一个不就完了么。

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/Line.vue
> +    const strokeWidth = computed(() => toNumber(props.strokeWidth ?? (isSmallSize.value ? 6 : 8)))
6，8 常量。

2021-03-13 04:46 UTC, danranVm commented on packages/components/progress/src/Line.vue
> +    addIconDefinitions([CheckCircleFilled, CloseCircleFilled])
同上

2021-03-16 01:13 UTC, hangboss1761 commented on packages/components/progress/src/Circle.vue
> +    const strokeWidth = computed(() => toNumber(props.strokeWidth, 6))
strokeWidth的默认宽度在line里面是8，在circle里面是6

如果放在globalConfig里面需要有两个属性来体现，并且他们的属性名不可能都是strokeWidth，一致性得不到保障

个人觉得这个不适合作为globalConfig

2021-03-16 01:14 UTC, hangboss1761 commented on packages/components/progress/src/types.ts
> +  success?: ProgressSuccess
个人觉得拆开没有明显的积极意义，建议与ant保持一致即可

2021-03-16 01:15 UTC, hangboss1761 commented on packages/components/progress/src/util.ts
> +    from = '#3366ff', // @primary-color
js主题变量的方案可以另起一个issue跟踪，待方案确认后同意修改此类问题

2021-03-16 01:22 UTC, danranVm commented on packages/components/progress/src/Circle.vue
> +    const strokeWidth = computed(() => toNumber(props.strokeWidth, 6))
ok, 那在组件内部定义个常量吧。

2021-03-16 02:31 UTC, danranVm commented on packages/components/progress/src/types.ts
> +  success?: ProgressSuccess
react 是手动 setState 的，所有他们直接修改 object 的内的值没问题，
但是对于 vue 来说，如果你的 props 是一个 object，那么就得修改props 的引用才能触发变更。
通常 `successStrokeColor` 定义好 就不会变的，改变的只有 `successPercent`, 
```html
<ix-progress successStrokeColor="red" :successPercent="successPercent" />
setup() {
  const successPercent = ref(0)
  setTimeout(()=>{
    successPercent.value += 10
  },1000)
  return {successPercent}
}
```
按照现有的写法
```html
<ix-progress :success="success" />
setup() {
  const success = ref({ StrokeColor:'red',Percent:0 })  // 这里可以用 reactive 代替，可以做到上述的效果，但是 reactive 的心智负担还是比 ref 严重。
  setTimeout(()=>{
    success .value = {StrokeColor:'red',Percent:success.value.Percent + 10 }
  },1000)
  return {success }
}
```

2021-03-17 09:14 UTC, danranVm approved these changes
LGTM.

2021-03-17 09:19 UTC, merged