feat(comp:select): add selelct component
IduxFE/idux pull request #255
Opened 2021-03-22 13:53 UTC by danranVm

fix #212 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-03-23 09:13 UTC, LaamGinghong requested changes
2个问题

2021-03-23 09:13 UTC, LaamGinghong commented on packages/cdk/overlay/src/useModifiers.ts
> +  arrow: HTMLElement | null
非必填

2021-03-23 09:13 UTC, LaamGinghong commented on packages/cdk/overlay/src/useOverlay.ts
> +/* eslint-disable indent */
这句？

2021-03-23 09:14 UTC, LaamGinghong commented
我只看overlay的，其他的我不看，我没参与select的API评审，我不知道你设计是怎样的

2021-03-23 09:41 UTC, danranVm commented
> 我只看overlay的，其他的我不看，我没参与select的API评审，我不知道你设计是怎样的

overlay 的已经单独提 PR， #258

2021-03-29 01:27 UTC, lwh2015 commented on packages/components/select/demo/CustomLabel.vue
> +      { label: 'Ie', value: 'ie' },
```suggestion
      { label: 'IE', value: 'ie' },
```
从英文的角度上来讲，英文的首字母缩写应该是采用大写的形式，不等同于英文第一个字母大写

2021-03-29 01:27 UTC, lwh2015 commented on packages/components/select/index.ts
> +
```suggestion
IxSelect.install = (app: App): void => {
  app.component(IxSelect.name, IxSelect)
}

IxOption.install = (app: App): void => {
  app.component(IxOption.name, IxOption)
}

IxOptionGroup.install = (app: App): void => {
  app.component(IxOptionGroup.name, IxOptionGroup)
}

```
参照组件最新的注册写法

2021-03-29 01:29 UTC, lwh2015 commented on packages/components/select/demo/CustomLabel.vue
> +      { label: 'Ie', value: 'ie' },
顺带补充一点，Ie，为马耳他语中的一个二合字母。 QAQ

2021-03-29 03:48 UTC, zymoplastic commented on packages/components/select/src/Select.vue
> +    <div v-if="suffix || $slots.suffix || !multiple" class="ix-select-suffix">
这个地方为什么多选默认不展示图标, 有什么场景吗?

2021-03-29 04:57 UTC, zymoplastic commented on packages/components/select/src/Select.vue
> +      >
这个地方有一个小的设计问题我觉得可以探讨一下: 是否将单选和多选的 `selectShowItem` 封装在一起?

我个人的看法是不封装在一起.

单选的 `item` 的功能很少: 一个插槽, 一个判断右边(以后或许有左边) `padding` 的样式, 一个省略号样式, 其它基本没了.
而多选 `item` 的功能就多了, 它是一个 `tagList` 里面的一个项, 具备单独的功能和样式, 后面很可能修改或者增加功能.

单选和多选相似的地方是很平凡的(插槽, 省略号), 而不同是很多的并且是概念和组件业务上的, 拆开实现分离了变与不变, 只是模板多了一个分支和几行代码, 但是在 js 和 css 中却是减轻了心智负担和改动引发的可能性

如 js 中计算一些值就变得简单 , css 里面也不需要用多选做为前缀去大量覆盖, 后面修改和添加新功能的时候也不用把单选多选一起再测一遍.

2021-03-29 07:33 UTC, zymoplastic commented on packages/components/select/src/Option.vue
> +    const visible = computed(() => {
现在的显示是每个 `option` 自己内部取遍历判断, 可以考虑在外面生成 `options` 数组的地方根据过滤直接生成新的数组

2021-03-29 07:41 UTC, zymoplastic commented on packages/components/select/src/Option.vue
> +    const visible = computed(() => {
现在的显示是每个 `option` 自己内部判断, 对于使用 `props: options` 进行配置而不是 `slot` 的用户, 
可以考虑在外面生成 `options` 数组的地方根据过滤直接生成新的数组, 或者算完了传一个是否显示的 `flag`, 以提高性能, 其它一些属性的计算也是类似的

2021-03-29 08:38 UTC, zymoplastic commented on packages/components/select/src/OptionGroup.vue
> +    const visible = computed(() => showItemCount.value > 0)
`group` 的显示与否应该取决于下面有没有 `options` 吗? 我个人觉得这个只是一个样式容器, 不需要添加这个逻辑

2021-04-10 01:35 UTC, danranVm commented on packages/components/select/src/Option.vue
> +    const visible = computed(() => {
这里的代码后面回重构掉，有考虑过你说的实现方式。

2021-04-10 01:40 UTC, danranVm commented on packages/components/select/src/Select.vue
> +      >
单独提个 issue 讨论？要改的话，改动还不小。

2021-04-11 03:42 UTC, danranVm commented on packages/components/select/src/Select.vue
> +    <div v-if="suffix || $slots.suffix || !multiple" class="ix-select-suffix">
这次是参考的 antd 的设计，后面看我们自己的设计规范是怎么样的，再做调整吧。

2021-04-11 04:05 UTC, merged