fix(cdk: click-outside): fix click-outside bug
IduxFE/idux pull request #264
Opened 2021-03-24 11:11 UTC by LaamGinghong

fix #245

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-03-24 11:12 UTC, LaamGinghong commented
我重写了测试用例，你看看

2021-03-25 01:38 UTC, danranVm requested changes

2021-03-25 01:38 UTC, danranVm commented on packages/cdk/click-outside/__tests__/clickOutside.spec.ts
> +import { IxButton } from '@idux/components/button'
不要用 ix-button 吧，就普通的 button 不就完了，你这样会让 cdk 的 test 依赖 components...
我前两天给你删了的，你又给我整回来了。

demo 里 可以用。

2021-03-25 01:38 UTC, danranVm commented on packages/cdk/click-outside/docs/Index.zh.md
> +type ClickOutsideHandler = () => void
```suggestion
type ClickOutsideHandler = (e: Event) => void
```

2021-03-25 01:38 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +      return
29 和 42-43 行，单测没覆盖，不好覆盖吗？

2021-03-25 01:38 UTC, danranVm commented on packages/cdk/click-outside/src/useClickOutside.ts
> +  excludes: HTMLElement[]
```suggestion
  exclude: HTMLElement[]
```

不用带 s 把，没见过带 s 的。。。

2021-03-25 01:38 UTC, danranVm commented on packages/cdk/utils/typeof.ts
> +export function isObject<T = Record<any, any>>(val: unknown): val is T {
这个改回去，我之前也是这么写的，有个地方的 ts 推导会报错。

2021-03-25 01:54 UTC, LaamGinghong commented on packages/cdk/click-outside/src/useClickOutside.ts
> +      return
先忽略

2021-03-25 02:08 UTC, merged