feat(comp:tag): 新增tag组件
IduxFE/idux pull request #282
Opened 2021-04-06 15:59 UTC by Gilbert5210

fix: https://github.com/IduxFE/idux/issues/29

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-04-08 08:23 UTC, danranVm requested changes

2021-04-08 08:23 UTC, danranVm commented on packages/components/tag/src/Tag.vue
> +const PresetStatusColorRegex = new RegExp(`^(${PresetStatusColorTypes.join('|')})$`)
参考 isPresetColor 写一个 isStatusColor 吧。

2021-04-08 08:23 UTC, danranVm commented on packages/components/tag/src/types.ts
> +export const PresetStatusColorTypes = ['success', 'processing', 'error', 'default', 'warning']
```suggestion
export const PresetStatusColorTypes = ['pending', 'success',  'warning',  'error']
```
这个也移到 color.ts 里吧 processing 改成 pending
另外在 default.less 的 `@info-color: @primary-color;` 这一行后面加一个 `@pending-color: @primary-color;`

2021-04-08 08:23 UTC, danranVm commented on packages/components/tag/style/index.less
> +  padding: 2px 8px;
很多都可以定义成变量的 less, 都定义成变量吧， 参考一下其他组件。

2021-04-08 08:23 UTC, danranVm commented on packages/components/tag/style/index.less
> +  color: #000;
这个不是 gen 生成的吗，不应该删掉？

2021-04-08 08:23 UTC, danranVm commented on packages/components/tag/src/Tag.vue
> +    }
```suggestion
    const tagStyle = computed(()=>{
      const color = props.color
      const isPresetOrStatus = isPresetColor(color) || isStatusColor(color)
      return { backgroundColor:  isPresetOrStatus ? undefined : color }
    })
```

2021-04-08 08:23 UTC, danranVm commented on packages/components/tag/src/Tag.vue
> +    }
删除。

2021-04-14 11:33 UTC, Gilbert5210 commented on packages/components/tag/src/Tag.vue
> +  </div>
你这个就很棒，爱了

2021-04-14 12:06 UTC, Gilbert5210 commented on packages/components/tag/src/Tag.vue
> +const PresetStatusColorRegex = new RegExp(`^(${PresetStatusColorTypes.join('|')})$`)
这个可以有，直接卸载color.ts上哟

2021-04-14 12:23 UTC, Gilbert5210 commented on packages/components/tag/style/index.less
> +  padding: 2px 8px;
get

2021-04-17 15:59 UTC, danranVm requested changes

2021-04-17 15:59 UTC, danranVm commented on packages/components/utils/src/colors.ts
> +export const PresetStatusColorTypes = ['pending', 'success', 'warning', 'error'] as const
```suggestion
export const StatusColor = ['pending', 'success', 'warning', 'error'] as const

export type StatusColorType = ElementOf<typeof StatusColor>
```

2021-04-17 15:59 UTC, danranVm commented on packages/components/tag/src/Tag.vue
> +    const classes = useClasses(props, _isPresetColor())
```suggestion
    const config = useGlobalConfig('tag')
    const classes = useClasses(props, config,  isPresetOrStatusColor)
```

2021-04-17 15:59 UTC, danranVm commented on packages/components/tag/src/Tag.vue
> +    }
```suggestion
    const isPresetOrStatusColor = computed(() => {
       const color = props.color
       return isPresetColor(color) || isStatusColor(color)
     })
```

2021-04-17 15:59 UTC, danranVm commented on packages/components/tag/src/Tag.vue
> +      return { backgroundColor: isPresetOrStatus ? undefined : color }
```suggestion
      return { backgroundColor: isPresetOrStatusColor.value ? undefined : props.color }
```

2021-04-17 15:59 UTC, danranVm commented on packages/components/tag/src/types.ts
> +export interface TagOriginalProps {
```suggestion
export interface TagProps {
```

2021-04-17 15:59 UTC, danranVm commented on packages/components/tag/src/types.ts
> +  isRound: boolean
```suggestion
  checkAble?: boolean
  isRound?: boolean
```
这两个 props 支持一下全局配置

2021-04-17 15:59 UTC, danranVm commented on packages/components/tag/src/Tag.vue
> +}
```suggestion
const useClasses = (props: TagProps, config:TagConfig, isPresetOrStatusColor: ComputedRef<boolean>) => {
  return computed(() => {
    const checkable = props.checkable ?? config.checkable
    const isRound = props.isRound ?? config.isRound
    const colorClass = `ix-tag-${props.color}`
    const presetFlag = isPresetColor && !props.checkAble
    return {
      'ix-tag': true,
      'ix-tag-round': props.isRound,
      [colorClass]: presetFlag,
      'ix-tag-has-color': props.color && !presetFlag,
      'ix-tag-checkable': checkAble,
      'ix-tag-checkable-checked': props.checked,
    }
  })
}
```

这里有个疑问，为什么 checkAble 状态下，就没有颜色了呢，

2021-04-17 16:01 UTC, danranVm commented
lint 和 build 的 CI 都挂了，你看下是什么原因

2021-04-25 08:01 UTC, Gilbert5210 commented on packages/components/tag/src/Tag.vue
> +    const classes = useClasses(props, _isPresetColor())
`closable`
`isRound`
全局配置暂时只支持这两个

2021-04-25 08:07 UTC, Gilbert5210 commented on packages/components/utils/src/colors.ts
> +export const PresetStatusColorTypes = ['pending', 'success', 'warning', 'error'] as const
这个没毛病

2021-04-25 08:34 UTC, Gilbert5210 commented on packages/components/tag/src/Tag.vue
> +}
因为可以被选中的时候的颜色统一为一种配色。

2021-04-25 08:44 UTC, Gilbert5210 commented on packages/components/tag/src/Tag.vue
> +    const classes = useClasses(props, _isPresetColor())
后面加上了checkable

2021-04-28 01:34 UTC, danranVm approved these changes
LGTM.

2021-04-28 01:37 UTC, merged