Feat steps shanny
IduxFE/idux pull request #286
Opened 2021-04-10 17:50 UTC by ShannyShanny

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-04-11 14:40 UTC, danranVm requested changes

2021-04-11 14:40 UTC, danranVm commented on packages/cdk/utils/src/vNode.ts
> +}
这个 `instance[key]` 是干什么的？感觉这个函数没必要。。。
而且感觉用法也不对。

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/docs/Index.zh.md
> +```active``` | 指定步骤条当前的活跃节点，从0开始计算 | ```number``` | 0 | - | -
```suggestion
`active` | 指定步骤条当前的活跃节点，从0开始计算 | `number` | `0` | - | -
```
单 ` 就好了，其他的都改下。

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/index.ts
> +// export type { ButtonMode, ButtonSize } from '@idux/components/config'
移除。

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/Step.tsx
> +    index: PropTypes.number,
这个 index 应该不能让通过 props 指定吧，应该是自动计算的。

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/types.ts
> +interface StepOriginalProps {
```suggestion
export interface StepProps {
```

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/types.ts
> +interface StepsOriginalProps {
```suggestion
export interface StepsProps {
```

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/types.ts
> +export type StepProps = Readonly<StepOriginalProps>
移除

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/types.ts
> +export type StepsProps = Readonly<StepsOriginalProps>
移除

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/steps.ts
> +export const progressDotSlotKey: InjectionKey<Slot> = Symbol()
```suggestion
export const stepsToken: InjectionKey<{props:StepsProps, progressDot:Slot }> = Symbol()
```
另外这个文件名字也改成 token.ts 吧。

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/Steps.tsx
> +    provide(progressDotSlotKey, progressDotSlot)
```suggestion
    provide(stepsToken, { props, progressDot: slots.progressDot})
```

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/Steps.tsx
> +  setup(props, context: SetupContext) {
```suggestion
  setup(props:StepsProps, { slots }) {
```

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/Steps.tsx
> +    size: PropTypes.oneOf(['medium', 'small'] as const).def('medium'),
有一些props 可以支持全局配置的，参考一下其他组件。useGlobalConfig

2021-04-11 14:40 UTC, danranVm commented on packages/components/steps/src/Steps.tsx
> +    let stepsSlot = getSlotNodes(context.slots);
删除。没必要，render 里也能拿得到。

2021-05-04 15:32 UTC, ShannyShanny commented on packages/components/steps/src/Step.tsx
> +    index: PropTypes.number,
是通过父组件自动计算后，传进来的

2021-05-04 15:34 UTC, ShannyShanny commented on packages/components/steps/src/Steps.tsx
> +    let stepsSlot = getSlotNodes(context.slots);
有必要，用于兄弟slot通讯

2021-05-07 01:24 UTC, ShannyShanny commented on packages/components/steps/src/Steps.tsx
> +    let stepsSlot = getSlotNodes(context.slots);
stepsSlot的已修改

2021-05-11 03:02 UTC, merged