feat(comp: collapse): add collapse component
IduxFE/idux pull request #292
Opened 2021-04-18 07:58 UTC by Usualminds

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-04-19 07:40 UTC, danranVm requested changes

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/Collapse.vue
> +    return { ...toRefs(state), handleChange }
```suggestion
```
template 中没有用到，这里不用 return

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/Collapse.vue
> +    const accordionConfig = props.accordion ?? collapseConfig.accordion
```suggestion
    const accordion = computed(()=> props.accordion ?? collapseConfig.accordion)
```

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/Collapse.vue
> +    )
```suggestion
    const activeNames = ref<string[]>([])

    watch(
      () => props.active,
      value => {
        activeNames.value = toArrar(value)
      },
    )
```

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/Collapse.vue
> +      emitCommonEvents(activeNames)
```suggestion
      if (accordion.value) {
        const value = name === activeNames.value[0] ? [] : [name]
        activeNames.value = value
        emitCommonEvents(value)
        return
      }
      
      const _index = activeNames.value.indexOf(name)

      if (_index > -1) {
        activeNames.value.splice(_index, 1)
      } else {
        activeNames.value.push(name)
      }

      emitCommonEvents(activeNames.value)
```

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/CollapsePanel.vue
> +    }"
可以考虑抽一下。

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/CollapsePanel.vue
> +    </div>
可以考虑抽成内部的子组件

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/CollapsePanel.vue
> +    })
```suggestion
    const isActive = computed(() => activeNames.value.includes(props.name))
```
对 props 使用解构会失去响应式，activeNames 是父组件注入的。

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/Collapse.vue
> +    provide(collapseInjectionKey, props)
```suggestion
    provide(collapseInToken, { activeNames, handleChange, borderless: toRef(props, 'borderless')})
```

2021-04-19 07:40 UTC, danranVm commented on packages/components/collapse/src/Collapse.vue
> +    provide(collapseInjectionKey, props)
合并成一个吧，然后 subject 感觉不是很有必要用。

2021-04-24 05:26 UTC, Usualminds commented on packages/components/collapse/src/CollapsePanel.vue
> +    </div>
这块逻辑抽到子组件 `IxCollapsePanelHeader` 中

2021-04-24 05:58 UTC, Usualminds commented on packages/components/collapse/src/Collapse.vue
> +    provide(collapseInjectionKey, props)
合并到一个，provide 直接提供父组件的 props 过去，子组件按需获取
```
provide(collapseInjectionKey, { props, handleChange })
```

2021-04-24 06:28 UTC, Usualminds commented
@danranVm 问题已修改，有空 review 下

2021-04-24 15:22 UTC, danranVm approved these changes
没什么问题了，不过 build 和 test 的CI 还是挂掉的。
有空处理下。

2021-04-25 14:03 UTC, merged