refactor(comp:space): use tsx
IduxFE/idux pull request #317
Opened 2021-05-12 12:00 UTC by danranVm

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-05-13 02:52 UTC, LaamGinghong requested changes

2021-05-13 02:52 UTC, LaamGinghong commented on packages/cdk/utils/src/vNode.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
reason

2021-05-13 02:52 UTC, LaamGinghong commented on packages/cdk/utils/src/vNode.ts
> +    (isText(node) && (node as any).children.trim() === '')
应该可以做严格的类型校验

2021-05-13 02:52 UTC, LaamGinghong commented on packages/components/space/src/space.tsx
> +    const size$$ = computed(() => props.size ?? config.size)
这种命名规范可以讨论一下，或者不使用计算，放到render里面

2021-05-13 02:52 UTC, LaamGinghong commented on packages/cdk/utils/src/vNode.ts
> +}
这个文件覆盖率好像有点低啊

2021-05-15 14:25 UTC, danranVm commented on packages/cdk/utils/src/vNode.ts
> +    (isText(node) && (node as any).children.trim() === '')
做不了， vue 没有导出相关的类型。

2021-05-15 14:25 UTC, danranVm commented on packages/cdk/utils/src/vNode.ts
> +}
新增的几个函数没加单测，后面补吧。

2021-05-15 14:25 UTC, danranVm commented on packages/components/space/src/space.tsx
> +    const size$$ = computed(() => props.size ?? config.size)
之前就讨论过的，就是这个命名。后面跟两个 $$

2021-05-15 14:25 UTC, merged