feat(comp: overlay): overlay
IduxFE/idux pull request #381
Opened 2021-07-20 14:13 UTC by LaamGinghong

rebuild tooltip
rebuild popover

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-07-24 03:04 UTC, danranVm requested changes

2021-07-24 03:04 UTC, danranVm commented on packages/components/popover/src/hooks.ts
> +    return {
不是很推荐这种写法，会产生没必要的 render

2021-07-24 03:04 UTC, danranVm commented on packages/components/popover/src/types.ts
> +  'onUpdate:visible': IxPropTypes.func<(visible: boolean) => void>().def(() => {}),
```suggestion
  'onUpdate:visible': IxPropTypes.emit<(visible: boolean) => void>(),
```

2021-07-24 03:04 UTC, danranVm commented on packages/components/tooltip/src/types.ts
> +  'onUpdate:visible': IxPropTypes.func<(visible: boolean) => void>().def(() => {}),
```suggestion
  'onUpdate:visible': IxPropTypes.emit<(visible: boolean) => void>(),
```

2021-07-24 03:04 UTC, danranVm commented on packages/components/tooltip/src/hooks.ts
> +      props['onUpdate:visible'](value)
callEmit

2021-07-24 03:04 UTC, danranVm commented on packages/components/popover/src/hooks.ts
> +      props['onUpdate:visible'](value)
callEmit

2021-07-24 03:32 UTC, danranVm commented on packages/components/_private/overlay/src/Overlay.tsx
> +        <IxPortal target={`${clsPrefix}-container`}>
```suggestion
        <IxPortal target={`${clsPrefix}-container`} load={visibility}>
```

2021-07-24 03:46 UTC, LaamGinghong commented on packages/components/_private/overlay/src/Overlay.tsx
> +  directives: { clickOutside },
components可以不用要，但是指令必须要，因为下面代码用的是字符串定义指令
![image](https://user-images.githubusercontent.com/33472924/126856463-bb86086b-bd7d-42f9-bcc0-2dc14ed275a5.png)

2021-07-24 03:56 UTC, LaamGinghong commented on packages/components/popover/src/hooks.ts
> +    return {
不改

2021-07-24 04:06 UTC, LaamGinghong commented on packages/components/_private/overlay/src/Overlay.tsx
> +        <IxPortal target={`${clsPrefix}-container`}>
下一个pr再改

2021-07-24 04:11 UTC, LaamGinghong commented on packages/components/_private/overlay/src/Overlay.tsx
> +  directives: { clickOutside },
下一个pr再改

2021-07-24 04:17 UTC, danranVm approved these changes
LGTM.

2021-07-24 04:17 UTC, merged

2021-07-27 02:21 UTC, danranVm commented on packages/components/_private/overlay/src/Overlay.tsx
> +    }
```ts
     const triggerNode =  getFirstValidNode(getSlotNodes(slots, 'trigger')
      if (!triggerNode) {
        Logger.error('Trigger msut is valid node.')
        return null
      }
      const contentNode = slots.overlay?.()
      if (!getFirstValidNode(contentNode)) {
        return triggerNode
      }
```
- 如果没有有效的 trigger 插槽，返回 null
- 如果没有有效的 overlay 插槽， 返回 trigger ( 比如 tooltip 的 title 为空时)
- trigger 插槽改名为 default
- overlay 插槽改名为 content

2021-07-27 02:21 UTC, danranVm commented on packages/components/_private/overlay/src/Overlay.tsx
> +    )
只要给 最外层加一个 clsPrefix 就好了，arrow 和 content 都不需要加，
content 的 dom 不应该加在这里。

2021-07-27 02:21 UTC, danranVm commented on packages/components/_private/overlay/src/Overlay.tsx
> +            {destroyOnHide ? visibility && content : <div v-show={visibility}>{content}</div>}
这里可以优化以下， destroyOnHide  && !visibility  的时候，提前返回 null ，避免不必要的创建 content vNode

2021-07-27 02:32 UTC, LaamGinghong commented on packages/components/_private/overlay/src/Overlay.tsx
> +    }
可以

2021-07-27 02:32 UTC, LaamGinghong commented on packages/components/_private/overlay/src/Overlay.tsx
> +    )
> content 的 dom 不应该加在这里

这句话没看懂

2021-07-27 03:32 UTC, danranVm commented on packages/components/_private/overlay/src/Overlay.tsx
> +    )
就是直接 `{overlay}` 就好了，不需要额外包一层 dom 节点。overlay 的内容应该是完全由子组件控制的。

2021-07-27 05:13 UTC, LaamGinghong commented on packages/components/_private/overlay/src/Overlay.tsx
> +    )
包一层是为了控制样式而已，不然的话得把classname复制到overlay这个虚拟节点里面，其实两种方案都可以，不过第二种的话可能要调整一下样式

2021-07-27 05:14 UTC, LaamGinghong commented on packages/components/_private/overlay/src/Overlay.tsx
> +            {destroyOnHide ? visibility && content : <div v-show={visibility}>{content}</div>}
应该还好，毕竟visibility的时候不会把content装进虚拟dom树，那点小规模的内存影响应该不会很大