refactor(comp:result): update to tsx, modify icon
IDuxFE/idux pull request #502
Opened 2021-11-09 10:01 UTC by sallerli1

change template to tsx render function
add status icon global config to result component

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Result component is currently written as vue SFC, and with templates, which is inconsistent with the coding style
Result component doesn't include the ability to configure icons under certain status globally
Result component status icons is inconsistent with those in modal component

## What is the new behavior?
Result component has been rewritten using tsx file with tsx render function returned in setup function
An global icon configuration identical with that in modal global configuration has been included
Default icons has been modified to be consistent with modal component icons

## Other information
component snapshot has been updated
icon names in result component test suits has been updated

2021-11-09 10:39 UTC, danranVm requested changes

2021-11-09 10:39 UTC, danranVm commented on packages/components/result/__tests__/result.spec.ts
> +    expect(wrapper.findComponent(IxIcon).props().name).toEqual('info-circle-filled')
```suggestion
   expect(wrapper.find('.ix-icon-info-circle-filled').exists()).toBe(true)
```
断言 icon 的地方，都统一换成这种形式吧。

2021-11-09 10:39 UTC, danranVm commented on packages/components/result/src/Result.tsx
> +  success: 'check-circle-filled',
默认图标改了的话，记得改一下 icon/src/dependencies.ts 这个文件里的依赖图标，

2021-11-09 11:49 UTC, sallerli1 commented on packages/components/result/__tests__/result.spec.ts
> +    expect(wrapper.findComponent(IxIcon).props().name).toEqual('info-circle-filled')
Result测试用例中的断言已修改

2021-11-10 01:27 UTC, danranVm approved these changes

2021-11-10 01:28 UTC, merged