feat(comp:alert): add alert component
IDuxFE/idux pull request #520
Opened 2021-11-14 03:58 UTC by brenner8023

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

add Alert component

## What is the new behavior?

### IxAlert

#### Props

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `type` | 设置提示类型 | `'success' \| 'info' \| 'warning' \| 'error'` | `info` | - |- |
| `closable` | 信息提示是否可关闭 | `boolean` | `false` | ✅ |- |
| `transition-name` | 设置动画效果 | `string` | - | - | - |
| `close-icon` | 自定义关闭按钮 | `string \| #closeIcon` | `close` | - | - |
| `icon` | 自定义图标 | `string \| #icon` | - | ✅ | 若要隐藏图标则传空串 |
| `title` | 信息提示内容 | `string \| #default` | - | - |- |
| `description` | 辅助性文字介绍 | `string \| #description` | - | - |- |
| `on-before-close` | 关闭提示前会触发的回调函数 | `() => boolean \| Promise<boolean>` | `() => true` | - | - |
| `on-close` | 关闭提示会触发的回调函数 | `() => void` | - | - | - |

## Other information

Missing unit test

2021-11-15 05:05 UTC, danranVm requested changes

2021-11-15 05:05 UTC, danranVm commented on packages/components/alert/src/types.ts
> +  onBeforeClose: IxPropTypes.func<() => boolean | Promise<boolean>>().def(() => true),
```suggestion
  onBeforeClose: IxPropTypes.emit<() => boolean | Promise<boolean> | void>(),
```

2021-11-15 05:05 UTC, danranVm commented on packages/components/alert/style/mixin.less
> +.alert-icon-color (@type, @color) {
这两个 mixin 是不是可以合并成一个？

2021-11-15 05:05 UTC, danranVm commented on packages/components/alert/src/Alert.tsx
> +  }
```suggestion
  const [pageIndex, setPagIndex ] = useState(0)
  const [pageTotal, setPageTotal ] = useState(1)
  const isShowPagination = computed(() => pageTotal.value > 1)
  const isLeftDisabled = computed(() => pageIndex.value <= 0)
  const isRightDisabled = computed(() => pageIndex.value + 1 >= pageTotal.value)
  const pageText = computed(() => `${pageIndex.value + 1}/${pageTotal.value}`)

  const offsetPageIndex = (offset: -1 | 1) => {
    if (offset === -1 && isLeftDisabled.value) {
      return
    }
    if (offset === 1 && isRightDisabled.value) {
      return
    }
    pageIndex.value += offset
  }
```

2021-11-15 06:41 UTC, danranVm commented on packages/components/alert/src/Alert.tsx
> +      setPageTotal(children.length)
```suggestion
  const chilren = computed(()=> slots.default?.() || NoopArray)
  const pageTotal = computed(() => chilren.value.length)
```
这里可以改成这样， render 函数外面用 computed 缓存起来

2021-11-16 01:01 UTC, brenner8023 commented on packages/components/alert/__tests__/alert.spec.ts
> +    })
fix

2021-11-16 01:01 UTC, brenner8023 commented on packages/components/alert/__tests__/alert.spec.ts
> +    await nextTick()
fix

2021-11-16 01:01 UTC, brenner8023 commented on packages/components/alert/__tests__/alert.spec.ts
> +    })
fix

2021-11-16 01:02 UTC, brenner8023 commented on packages/components/alert/__tests__/alert.spec.ts
> +    })
fix

2021-11-16 01:02 UTC, brenner8023 commented on packages/components/alert/demo/Animation.vue
> +  <IxAlert closable transition-name="fade">我之前还没发现，当我发现的时候我已经发现了。</IxAlert>
已改成内置一种

2021-11-16 01:04 UTC, brenner8023 commented on packages/components/alert/src/Alert.tsx
> +      hasDescription.value = !!description
已删除`hasDescription`

2021-11-16 01:04 UTC, brenner8023 commented on packages/components/alert/src/Alert.tsx
> +    })
已修改

2021-11-16 01:05 UTC, brenner8023 commented on packages/components/alert/src/types.ts
> +  onBeforeClose: IxPropTypes.func<() => boolean | Promise<boolean>>().def(() => true),
fix

2021-11-16 01:05 UTC, brenner8023 commented on packages/components/alert/style/mixin.less
> +.alert-icon-color (@type, @color) {
合并成为`alert-status-color`

2021-11-16 01:06 UTC, brenner8023 commented on packages/components/alert/src/Alert.tsx
> +  }
这很react，已修改

2021-11-16 01:07 UTC, brenner8023 commented on packages/components/alert/src/Alert.tsx
> +      setPageTotal(children.length)
改成了`const children = computed(() => flattenNode(slots.default?.() ?? []))`

2021-11-16 01:13 UTC, danranVm approved these changes

2021-11-16 01:18 UTC, danranVm commented
需要解决一下 index.ts 的冲突，以及在 components.less 中，添加一下组件样式入口文件。

2021-11-16 07:02 UTC, danranVm approved these changes

2021-11-16 07:03 UTC, merged