feat(comp: skeleton): add Skeleton component
IDuxFE/idux pull request #548
Opened 2021-11-21 10:48 UTC by brenner8023

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

add Skeleton component

## What is the new behavior?

### IxSkeleton

#### SkeletonProps

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `animated` | 是否开启动画 | `boolean` | `true` | ✅ | - |
| `type` | 骨架的类型 | `'text' \| 'rect' \| 'round' \| 'circle'` | `text` | - | - |
| `loading` | 是否显示加载结束后的UI | `boolean` | `true` | - | - |
| `width` | 骨架的宽度 | `string \| number` | `text` | - | - |
| `height` | 骨架的高度 | `string \| number` | `text` | - | - |
| `repeat` | 骨架的重复次数 | `number` | `1` | - | - |

#### SkeletonSlots

| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| default | 展示加载结束后的UI | - | - |

## Other information

2021-11-22 01:38 UTC, danranVm requested changes

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/demo/Loading.md
> +支持使用`v-if`或者默认插槽实现切换UI，默认插槽实现会额外生成一个div。
这里其实不用 额外生成一个 div.

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/docs/Index.zh.md
> +| `repeat` | 骨架的重复次数 | `number` | `1` | - | - |
注意 props 的顺序，参见 https://github.com/IDuxFE/idux/issues/225

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/docs/Index.zh.md
> +#### SkeletonMethods
空的就移除掉。

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/src/Skeleton.tsx
> +    const style = computed(() => {
```suggestion
    const loaderStyle = computed(() => {
```

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/src/Skeleton.tsx
> +      }
```suggestion
      const { width, height, type } = props
      if (type === 'circle') {
        const size = convertCssPixel(width || height)
        return { width: size, height: size }
      }

      return {
        width: convertCssPixel(width),
        height: convertCssPixel(height),
      }
```

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/src/Skeleton.tsx
> +      return <div class={prefixCls}>{props.loading ? loaderList : slots.default?.()}</div>
```suggestion
      if(!props.loading) {
        return slots.default?.()
      }
      
      const prefixCls = mergedPrefixCls.value
      const loader = <div class={loaderClass.value} style={style.value}></div>
      const loaderList = Array.from({ length: props.repeat }).map(() => loader)

      return <div class={prefixCls} {...attrs}>{loaderList}</div>
```

这样就不会多一层 div

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/src/Skeleton.tsx
> +  name: 'IxSkeleton',
```suggestion
  name: 'IxSkeleton',
  inheritAttrs: false,
```
为了避免 attrs 被透传到默认插槽，所以这里要设置一下

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/src/Skeleton.tsx
> +  setup(props, { slots }) {
```suggestion
  setup(props, { attrs, slots }) {
```

2021-11-22 01:38 UTC, danranVm commented on packages/components/skeleton/style/index.less
> +@skeleton-prefix: ~'@{idux-prefix}-skeleton';
这行可以移除掉，在 prifix.less 里已经自动声明了。

2021-11-22 14:50 UTC, brenner8023 commented on packages/components/skeleton/demo/Loading.md
> +支持使用`v-if`或者默认插槽实现切换UI，默认插槽实现会额外生成一个div。
我的想法是，有额外生成一个 div，如果给骨架屏设置样式间距，样式间距对插槽内容也同样生效。

2021-11-22 14:51 UTC, brenner8023 commented on packages/components/skeleton/docs/Index.zh.md
> +| `repeat` | 骨架的重复次数 | `number` | `1` | - | - |
fix

2021-11-22 14:51 UTC, brenner8023 commented on packages/components/skeleton/docs/Index.zh.md
> +#### SkeletonMethods
已经移除了

2021-11-22 14:51 UTC, brenner8023 commented on packages/components/skeleton/src/Skeleton.tsx
> +    const style = computed(() => {
已修改

2021-11-22 14:52 UTC, brenner8023 commented on packages/components/skeleton/src/Skeleton.tsx
> +      }
已修改

2021-11-22 14:52 UTC, brenner8023 commented on packages/components/skeleton/src/Skeleton.tsx
> +      return <div class={prefixCls}>{props.loading ? loaderList : slots.default?.()}</div>
按修改建议改了

2021-11-22 14:53 UTC, brenner8023 commented on packages/components/skeleton/src/Skeleton.tsx
> +  name: 'IxSkeleton',
已加上

2021-11-22 14:53 UTC, brenner8023 commented on packages/components/skeleton/src/Skeleton.tsx
> +  setup(props, { slots }) {
已加上

2021-11-23 06:07 UTC, danranVm approved these changes

2021-11-23 06:13 UTC, merged