feat(comp: notification): add notification component
IDuxFE/idux pull request #552
Opened 2021-11-23 13:11 UTC by lo56ve

re #545

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-11-25 08:29 UTC, danranVm requested changes

2021-11-25 08:29 UTC, danranVm commented on packages/components/notification/src/NotificationProvider.tsx
> +  const { verticalOffset, horizontalOffset } = getDirectionOffset(offset)
```suggestion
 const offsets = isArray(offset) ? offset : [offset, offset]
  const [ verticalOffset, horizontalOffset ] = offsets.map(convertCssPixel)
```

2021-11-25 08:29 UTC, danranVm commented on packages/components/notification/src/NotificationProvider.tsx
> +    topEnd: 'ix-move-end',
ix 前缀通过 globalConfig 获取

2021-11-25 08:29 UTC, danranVm commented on packages/components/notification/src/NotificationProvider.tsx
> +            // 同个方位的已第一个的offset为基准
这个设定感觉不太合适。。。

2021-11-25 08:29 UTC, danranVm commented on packages/components/notification/src/NotificationProvider.tsx
> +        ...getRealObj(omit<NotificationOptions, 'onDestroy'>(item, ['onDestroy'])),
这种写法会造成一些不必要的响应式依赖，另外可读性也。。

2021-11-25 08:29 UTC, danranVm commented on packages/components/notification/src/NotificationProvider.tsx
> +  )
```suggestion
  const  notificationTypes = ['info', 'success', 'warning', 'error'] as const
  const [info, success, warning, error] = notificationTypes.map(type => {
    return (options?: Omit<NotificationOptions, 'type'>) => open({ ...options, type })
  })
```
要沉迷 reduce 呢，map 不香吗？

2021-11-25 08:29 UTC, danranVm commented on packages/components/notification/src/Notification.tsx
> +function getNode<T extends NotificationProps, K extends NotificationNodePropKey>(
这个函数有点过度封装了，即影响了可读性，也降低了执行效率（每次都会去创建 footer Node）。

2021-11-25 08:29 UTC, danranVm commented on packages/components/notification/src/NotificationProvider.tsx
> +    .set('bottomEnd', { bottom: verticalOffset, right: horizontalOffset })
const  positions = {
topStart: ['top', 'left'],
topEnd: ['top', 'right'],
bottomStart: ['bottom', 'left'],
bottomEnd: ['bottom', 'right'],
} as const // 定义到外面

const [ verticalPosition, horizontalPosition ] = positions[placement ]
return { [verticalPosition]:verticalOffset, [horizontalPosition]:horizontalOffset   }

2021-11-29 03:14 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +  success: 'check-circle',
声明 // staticIcons.ts  的作用是？

2021-11-29 03:15 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +  success: 'check-circle',
> 

声明 // staticIcons.ts 的作用是？

2021-11-29 03:16 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +  success: 'check-circle',
> 这个直接作为 defaultConfig 把 另外注意在 // staticIcons.ts 里声明一下。

声明 // staticIcons.ts 的作用是？

2021-11-29 13:06 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +  success: 'check-circle',
fix

2021-11-29 13:07 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +  slots: SetupContext['slots'],
fix

2021-11-29 13:07 UTC, lo56ve commented on packages/components/notification/docs/Index.zh.md
> +| `icon`           | 自定义通知图标                 | `string \| VNode`                                         | -          | -        | -                                                            |
fix

2021-11-29 13:07 UTC, lo56ve commented on packages/components/style/themes/default.less
> +/* notification -------------------------- */
fix

2021-11-29 13:08 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +            {placementGroup.value}
fix

2021-11-29 13:08 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +// 将通知按位置分类
fix

2021-11-29 13:08 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +  const { verticalOffset, horizontalOffset } = getDirectionOffset(offset)
fix

2021-11-29 13:08 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +            // 同个方位的已第一个的offset为基准
fix

2021-11-29 13:08 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +  )
fix

2021-11-29 13:08 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +    topEnd: 'ix-move-end',
fix

2021-11-29 13:09 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +        ...getRealObj(omit<NotificationOptions, 'onDestroy'>(item, ['onDestroy'])),
fix

2021-11-29 13:09 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +function getNode<T extends NotificationProps, K extends NotificationNodePropKey>(
fix

2021-11-29 13:09 UTC, lo56ve commented on packages/components/notification/src/NotificationProvider.tsx
> +    .set('bottomEnd', { bottom: verticalOffset, right: horizontalOffset })
fix

2021-11-29 13:09 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +    isShowIcon: computed(() => !!props.type),
fix

2021-11-30 01:13 UTC, lo56ve commented on packages/components/notification/src/Notification.tsx
> +const clsPrefix = 'ix-notification'
fix

2021-11-30 12:06 UTC, merged