feat(comp:prolayout): init pro components
IDuxFE/idux pull request #558
Opened 2021-11-30 09:51 UTC by lo56ve

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-12-07 06:59 UTC, danranVm commented on packages/components/menu/docs/Index.zh.md
> +| `overlayClassName` | 悬浮层的自定义 `class` | `string` | - | - | - |
我发现下面的 MenuSub 不是有这个 props 嘛

2021-12-07 06:59 UTC, danranVm commented on packages/components/menu/src/types.ts
> +export type IconParams = {
这个类型不应该定义在这，定义在 utils 里就好了。

2021-12-07 06:59 UTC, danranVm commented on packages/components/menu/style/themes/default.less
> +@menu-sider-collapsed-width: 64px;
改成 @menu-collapsed-width: 64px;

2021-12-07 06:59 UTC, danranVm commented on packages/pro/config/src/defaultConfig.ts
> +import type { CommonConfig, GlobalConfig, LayoutProConfig } from './types'
pro 里面的组件先暂不支持全局配置吧，后面看看怎么兼顾。不要全 copy 过来。

2021-12-07 06:59 UTC, danranVm commented on packages/pro/layout/docs/Index.zh.md
> +| -------------------- | ------------------------ | ------------------------------------------------------------ | --------------------- | -------- | -------------------------------------------------
你这个 md 是不是用了其他的格式化插件？ 参考下其他组件的文档，格式改一下，不然 review 起来好难看。。。

2021-12-07 06:59 UTC, danranVm commented on packages/pro/layout/index.ts
> +const IxLayoutProCtrl = LayoutProCtrl
看完你的整个实现，我感觉这个组件放到 components 里可能更好一些？
名字应该叫 IxLayoutSiderTrigger

2021-12-07 06:59 UTC, danranVm commented on packages/pro/layout/src/Layout.tsx
> +  name: 'IxLayoutPro',
这个组件太大了，需要拆一下。
可以参考一下 tree 组件的目录结构。
另外你的变量命名和类型命令，也参考一下其他组件，尽可能的风格保持一致。

2021-12-07 12:16 UTC, lo56ve commented on packages/components/menu/docs/Index.zh.md
> +| `overlayClassName` | 悬浮层的自定义 `class` | `string` | - | - | - |
是有，但layoutPro不直接使用MenuSub，而是通过dataSource来生成，所以需要Menu也支持一下

2021-12-07 12:50 UTC, lo56ve commented on packages/pro/layout/index.ts
> +const IxLayoutProCtrl = LayoutProCtrl
https://github.com/IDuxFE/idux/issues/587，另外提issue跟踪修改

2021-12-09 01:58 UTC, danranVm requested changes

2021-12-09 01:58 UTC, danranVm commented on packages/pro/layout/__tests__/layoutPro.spec.ts
> +    const customStringIconWrapper = LayoutProMount({
这种最好拆成一个新的 test

2021-12-09 01:58 UTC, danranVm commented on packages/pro/layout/__tests__/layoutPro.spec.ts
> +    const customRenderIconWrapper = LayoutProMount({
同上

2021-12-09 02:03 UTC, merged