feat(comp:upload): add file upload component
IDuxFE/idux pull request #669
Opened 2021-12-27 06:58 UTC by typistZxd

fix #605

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

add file upload component
## Other information

2022-01-05 07:42 UTC, danranVm requested changes
重点 review 了 API 的设计，代码实现细节我就没有仔细看了。

2022-01-05 07:42 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +### IxUploadFiles 上传文件列表展示
```suggestion
### IxUploadList
```

2022-01-05 07:42 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +| `icon` | 展示的icon   | `Record<file \| preview \| download \| remove \| retry, string \| boolean \| VNode`>  | `{file: true, remove: true, retry: true}` | ✅ | - |
```suggestion
| `icon` | 展示的icon   | `Record<file \| preview \| download \| remove \| retry, string \| VNode`>  | `{file: 'name', remove: 'name', retry: 'name'}` | ✅ | - |
```

2022-01-05 07:42 UTC, danranVm commented on packages/components/config/src/types.ts
> +  icon: Partial<Record<UploadIconType, string | boolean | VNode>>
```suggestion
  type: UploadListType
  icon: Partial<Record<UploadIconType, string | VNode>>
```

2022-01-05 07:42 UTC, danranVm commented on packages/components/config/src/defaultConfig.ts
> +    retry: true,
```suggestion
    file: true,
    remove: true,
    retry: true,
```
这三个改成默认的字符串

2022-01-05 07:42 UTC, danranVm commented on packages/components/upload/style/index.ts
> +import '../../style/index.less'
这个 index.ts 文件被干掉了，参考一下最新的（更新到最新代码） modal 组件 style 的目录结构。

2022-01-05 07:42 UTC, danranVm commented on packages/components/upload/index.ts
> +  UploadListPublicProps as UploadListProps,
```suggestion
  UploadComponent，
  UploadPublicProps as UploadProps,
  UploadListInstance,
  UploadListComponent
  UploadListPublicProps as UploadListProps,
```

这两个类型也要导出，同时修改一下 type.d.ts

2022-01-05 07:42 UTC, danranVm commented on packages/components/upload/src/List.tsx
> +    } as unknown as UploadToken)
```suggestion
    const { props: uploadProps, setSelectorVisible } = inject(uploadToken)!
```
这种只能在指定父组件内生效的组件，用 `!` 断言一下就好。

2022-01-05 08:00 UTC, danranVm reviewed
我发现三种类型对应的子组件其实也是差不多的，只不过是 item 不一样，我建议是不是抽 3 个不的 item 就好了。

2022-01-11 08:25 UTC, typistZxd commented
> 我发现三种类型对应的子组件其实也是差不多的，只不过是 item 不一样，我建议是不是抽 3 个不的 item 就好了。

三种类型相互之间存在不止item上的细节差异（比如`imageCard`类型和其余两种差异不止item，还存在自身特殊的selector等），为方便单个类型之后扩展，建议保留，也可为用户自定义列表提供样例

2022-01-11 08:29 UTC, typistZxd commented
@danranVm review已修改，请查看

2022-01-13 11:28 UTC, danranVm requested changes

2022-01-13 11:28 UTC, danranVm commented on packages/components/config/src/types.ts
> +  listType: UploadListType
```suggestion
  type: UploadListType
```

2022-01-13 11:28 UTC, danranVm commented on packages/components/upload/demo/MaxCount.vue
> +  <IxUpload v-model:files="files" action="/upload" :maxCount="maxCount">
demo 里的上传地址找个开源的 mock 服务？

2022-01-13 11:28 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +  e?: ProgressEvent
```suggestion
  response?: Response
  event?: ProgressEvent
```

2022-01-13 11:28 UTC, danranVm commented on packages/components/upload/src/Upload.tsx
> +      <div>
```suggestion
      const prefixCls = mergedPrefixCls.value
      <div  class={prefixCls }>
```

2022-01-13 11:28 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +  uid: VKey // 唯一标识
```suggestion
  key: VKey // 唯一标识
```

2022-01-13 11:28 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +  raw?: UploadRawFile
这个 UploadRawFile 又是啥？原生的 File ?

2022-01-13 11:28 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +  errorTip?: string // 小i报错提示文本
errorTip 和 error 是不是重复了？

2022-01-13 11:28 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +  filename: string
```suggestion
  name: string
```

2022-01-13 12:52 UTC, typistZxd commented on packages/components/upload/docs/Index.zh.md
> +  errorTip?: string // 小i报错提示文本
不重复，error包含完整的报错信息，errorTip是在列表展示的报错提示文本（需要由用户配置）

![image](https://user-images.githubusercontent.com/17819018/149333592-8af7598e-e2c3-4a7e-ade3-a980d9bd77ea.png)

2022-01-13 12:54 UTC, typistZxd commented on packages/components/upload/docs/Index.zh.md
> +  raw?: UploadRawFile
包含uid的原生File对象，用于在列表中查询UploadFile

2022-01-18 02:22 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +### IxUploadFiles
```suggestion
### IxUploadList
```

这个是写错了？

2022-01-18 02:22 UTC, danranVm commented on packages/components/upload/docs/Index.zh.md
> +| `onRequestChange` | 请求状态改变的钩子 | `(option: UploadRequestChangeOption) => void` | - | - | - |
我在想是不是可以把 onFileStatusChange 和 onRequestChange 合并成一个 onStatusChange ?

2022-01-18 04:17 UTC, typistZxd commented on packages/components/upload/docs/Index.zh.md
> +| `onRequestChange` | 请求状态改变的钩子 | `(option: UploadRequestChangeOption) => void` | - | - | - |
onFileStatusChange 描述文件的整个周期，onRequestChange描述的是单个请求生命周期，虽然有交集的部分但是含义和用途不同。如

- 请求开始前处理如加遮罩，属于请求范围，需要在onRequestChange的loadStart阶段
- onRequestChange的progress可以更新进度，而onFileStatusChange 一直是uploading状态不会改变

2022-01-18 06:23 UTC, merged