wip:refactor: move to pnpm
IDuxFE/idux pull request #745
Opened 2022-02-04 14:10 UTC by jackson-yyy

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [x] Other... Please describe: move to pnpm

## What is the current behavior?

using yarn

## What is the new behavior?
move to pnpm

## Other information

2022-02-07 03:36 UTC, danranVm requested changes
顺便改一下 `azure-pipelines.yml` 里面的命令？

2022-02-07 03:36 UTC, danranVm commented on packages/components/package.json
> +  "devDependencies": {
compoents 应该没有依赖这两个库，是 site 的依赖。

2022-02-07 03:36 UTC, danranVm commented on scripts/gulp/build/index.ts
> +    await copyFile(join(componentsDirname, 'bin.js'), join(componentsDistDirname, 'bin.js'))
这里好像不应该改动？

2022-02-09 01:56 UTC, jackson-yyy commented on packages/components/package.json
> +  "devDependencies": {
我搜了一下，components下是有引用的

2022-02-09 01:56 UTC, jackson-yyy commented on packages/components/package.json
> +  "devDependencies": {
> compoents 应该没有依赖这两个库，是 site 的依赖。

我搜了一下，components下是有引用的

2022-02-09 01:58 UTC, danranVm commented on packages/components/package.json
> +  "devDependencies": {
这两个是在 demo 里面用的，是输入 site 的代码。
components 的源码仅包含 src 目录下的。

2022-02-09 02:29 UTC, jackson-yyy commented on scripts/gulp/build/index.ts
> +    await copyFile(join(componentsDirname, 'bin.js'), join(componentsDistDirname, 'bin.js'))
pnpm在安装site依赖的时候，因为@idux/components是pnpm接管的package，会自动链接package/components目录，而不是从npm下载包，如果bin.js不在package/components目录下，npm的钩子会报错，因为@idux/components的package.json声明了bin

2022-02-12 09:30 UTC, liuzaijiang commented on package.json
>    },
看看是否需要把gulp给加上，我本地尝试的时候，告诉我没有安装gulp

2022-02-13 08:28 UTC, jackson-yyy commented on package.json
>    },
应该是有写glup的，是不是什么原因导致glup的bin没有生成？

2022-02-14 03:18 UTC, merged