feat(comp: button): add xs and lg sizes
IDuxFE/idux pull request #780
Opened 2022-03-01 12:16 UTC by liuzaijiang

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

The default size is changed to 'sm'

2022-03-02 07:19 UTC, danranVm commented on packages/components/button/src/Button.tsx
> +    const size = computed(() => props.size ?? groupProps.size ?? formContext?.size.value ?? 'sm')
这个会影响到所以使用 button 组件的其他组件，不能这么干吧。。。

2022-03-03 01:34 UTC, liuzaijiang commented on packages/components/style/variable/width.less
> +@width-xs: 56px;
checkbox 和 radio的button状态都需要有最小宽度

2022-03-03 01:35 UTC, liuzaijiang commented on packages/components/button/src/Button.tsx
> +    const size = computed(() => props.size ?? groupProps.size ?? formContext?.size.value ?? 'sm')
那就需要改为全局配置

2022-03-03 09:20 UTC, danranVm requested changes

2022-03-03 09:20 UTC, danranVm commented on packages/components/button/src/Button.tsx
> +    const size = computed(() => props.size ?? groupProps.size ?? formContext?.size.value ?? 'sm')
行吧，改成全局配置吧。

2022-03-07 12:13 UTC, merged