fix(comp: stepper): vertical style error without description
IDuxFE/idux pull request #784
Opened 2022-03-03 07:16 UTC by liuzaijiang

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

```
<template>
  <IxStepper :activeKey="2" vertical>
    <IxStepperItem status="finish" title="Finished" ></IxStepperItem>
    <IxStepperItem title="In Progress"></IxStepperItem>
    <IxStepperItem title="Waiting"></IxStepperItem>
  </IxStepper>
</template>
```
![image](https://user-images.githubusercontent.com/26105153/156515309-04d71174-9a27-455d-b60f-c4d0841287b9.png)

## What is the new behavior?

![image](https://user-images.githubusercontent.com/26105153/156515262-525cfdbe-df40-4847-a67a-39dd2e73b618.png)

## Other information

2022-03-03 09:37 UTC, danranVm requested changes

2022-03-03 09:37 UTC, danranVm commented on packages/components/stepper/src/Stepper.tsx
> +    provide(stepperToken, { props: reactive({ ...toRefs(props), size }), slots, activeKey, setActiveKey })
size 单独传一下就好了吧，没必要这么干。

2022-03-03 09:37 UTC, danranVm commented on packages/components/stepper/src/StepperItem.tsx
> +            {descriptionNode ? (
解决这个问题，没必要额外加个 DOM 吧，在垂直状态下，给 content 加个最小高度吧。

2022-03-03 12:48 UTC, liuzaijiang commented on packages/components/stepper/src/Stepper.tsx
> +    provide(stepperToken, { props: reactive({ ...toRefs(props), size }), slots, activeKey, setActiveKey })
不建议这样做，对于item来说size是属于parentProps的一部分

2022-03-04 02:49 UTC, danranVm approved these changes

2022-03-04 02:49 UTC, merged