Feat/select max label count responsive
IDuxFE/idux pull request #806
Opened 2022-03-18 11:57 UTC by hangboss1761

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

https://github.com/IDuxFE/idux/issues/756
## What is the new behavior?
https://github.com/IDuxFE/idux/issues/756
## Other information

2022-03-19 10:23 UTC, danranVm requested changes

2022-03-19 10:23 UTC, danranVm commented on packages/components/_private/overflow/src/types.ts
> +  maxLabelCount: IxPropTypes.oneOfType([IxPropTypes.number, IxPropTypes.oneOf(['responsive'])]).def(
```suggestion
  maxLabel: IxPropTypes.oneOfType([IxPropTypes.number, IxPropTypes.oneOf(['responsive'])]).def(
```

2022-03-19 10:23 UTC, danranVm commented on packages/components/_private/overflow/src/types.ts
> +  itemKey: IxPropTypes.string.isRequired,
```suggestion
  getKey: IxPropTypes.func<(item: unkown) => VKey>(). isRequired,
```
直接改成函数吧，在外面组件做转换。

2022-03-19 10:23 UTC, danranVm commented on packages/components/_private/overflow/src/Item.tsx
> +      props.onSizeChange?.(entry.target, props.itemKey ?? '')
用 callEmit

2022-03-19 10:23 UTC, danranVm commented on packages/components/_private/overflow/src/itemTypes.ts
> +export type OverflowItemInstance = InstanceType<DefineComponent<overflowItemProps>>
这个不用单独拆成一个文件，就放在 types 里面就好了，另外由于这个是内部组件，不需要用到这些类型，这些类型也可以不用定义。

2022-03-19 10:23 UTC, danranVm commented on packages/components/select/demo/MaxLabelCount.vue
> +      :options="options"
options 改成 datasource 吧

2022-03-19 10:23 UTC, danranVm commented on packages/components/select/demo/MaxLabelCount.vue
> +    <IxSelect v-model:value="value" :options="options" multiple></IxSelect>
这里设置下 maxLabel='3' , 有个对比。

2022-03-19 10:23 UTC, danranVm commented on packages/components/select/src/types.ts
> +  maxLabelCount: IxPropTypes.oneOfType([IxPropTypes.number, IxPropTypes.oneOf(['responsive'])]).def(
```suggestion
  maxLabelCount: IxPropTypes.oneOfType([IxPropTypes.number, IxPropTypes.oneOf(['responsive'])]).def(
  maxLabel: IxPropTypes.oneOfType([IxPropTypes.number, IxPropTypes.oneOf(['responsive'])]).def(
```

这里干脆直接改成 maxLabel 吧，然后保留 maxLabelCount， 在代码里做一下兼容，给个 logger，参考一下其他废弃的 api, 文档里 把 maxLabelCount 改成 maxLabel

2022-03-19 10:23 UTC, danranVm commented on packages/components/_private/overflow/src/Overflow.tsx
> +export default defineComponent({
把这个移到上面那堆代码的前面吧，更好阅读些。

2022-03-19 10:23 UTC, danranVm commented on packages/components/select/src/trigger/Selector.tsx
> +          <IxOverflow
这种是不是只有在多选的时候有意义？单选的时候需要吗？

2022-03-20 06:31 UTC, danranVm approved these changes

2022-03-20 06:37 UTC, danranVm commented on packages/components/select/src/trigger/Selector.tsx
> +        Logger.warn('components/select', '`maxLabelCount` was deprecated, please use slot `maxLabel` instead')
```suggestion
        Logger.warn('components/select', '`maxLabelCount` was deprecated, please use `maxLabel` instead')
```

2022-03-20 07:16 UTC, hangboss1761 commented on packages/components/select/src/trigger/Selector.tsx
> +        Logger.warn('components/select', '`maxLabelCount` was deprecated, please use slot `maxLabel` instead')
fix

2022-03-20 07:29 UTC, merged