refactor(comp:list): rebuild with tsx (#187)
IDuxFE/idux pull request #856
Opened 2022-04-23 08:41 UTC by qingshan-dev

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [x] Component style update
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2022-04-23 09:29 UTC, qingshan-dev reviewed
Self check is finish

2022-04-24 01:21 UTC, danranVm requested changes

2022-04-24 01:21 UTC, danranVm commented on packages/components/list/src/List.tsx
> +          'ix-list',
`ix` 的前缀别写死，参考一下其他组件的。

2022-04-24 01:21 UTC, danranVm commented on packages/components/list/src/List.tsx
> +    }
这些都不要吧，内部不去维护这个状态了，用户自己控制 loading 就好了。

2022-04-24 01:22 UTC, danranVm commented on packages/components/list/src/List.tsx
> +  emits: ['loadMore'],
这个干掉，如果有事件的话，声明在 props 中，参考一下其他组件。

2022-04-24 15:42 UTC, qingshan-dev commented on packages/components/list/src/List.tsx
> +          'ix-list',
已使用common.prefixCls

2022-04-24 15:42 UTC, qingshan-dev commented on packages/components/list/src/List.tsx
> +    }
使用 footer 替换使用, 减少内部代码体积

2022-04-24 15:43 UTC, qingshan-dev commented on packages/components/list/src/List.tsx
> +  emits: ['loadMore'],
已删除

2022-04-25 07:50 UTC, danranVm approved these changes
LGTM

2022-04-25 07:51 UTC, merged