feat(cdk:scroll, comp:transfer, pro:transfer): add autoHeight support for virtualScroll, refactor transfer style
IDuxFE/idux pull request #920
Opened 2022-05-19 14:48 UTC by sallerli1

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## What is the current behavior?
虚拟滚动无法自适应容器高度
穿梭框无法自适应容器高度

## What is the new behavior?
增加CdkVirtualScroll组件的 autoHeight 属性，使其自适应容器高度
修改穿梭框与高级穿梭框样式，使穿梭框body可以自适应撑满高度

## Other information

2022-05-23 02:54 UTC, danranVm requested changes

2022-05-23 02:54 UTC, danranVm commented on packages/cdk/scroll/src/virtual/VirtualScroll.tsx
> +    const useVirtual = computed(() => props.virtual && props.itemHeight > 0)
```suggestion
    const mergedVirtual = computed(() => props.virtual && props.itemHeight > 0 &&  (props.height > 0 || props.autoHeight))
```
另外我想把 virtual 改成 disabled, 就是废弃掉 virtual, 用 disabled 代替

2022-05-23 02:54 UTC, danranVm commented on packages/cdk/scroll/src/virtual/composables/useContainerHeight.ts
> +  return containerHeight
```suggestion
  const [ height, setHeight ] = useState(0)
  useResizeObserver(containerRef,  (entry) => {
      const { contentRect } = entry
      setHeight(contentRect.height)
  })
   // 这一行理论上可以删掉的，你试一下，如果删不掉，就把上面的回调函数取个名字
  // onMounted(() => nextTick(syncContainerHeight))

  return computed(() => props.height ?? height.value)
```

2022-05-23 02:54 UTC, danranVm commented on packages/cdk/scroll/src/virtual/composables/useContainerHeight.ts
> +export function useContainerHeight(props: VirtualScrollProps, containerRef: Ref<HTMLElement | undefined>): Ref<number> {
```suggestion
export function useContainerHeight(props: VirtualScrollProps, containerRef: Ref<HTMLElement | undefined>): ComputedRef<number> {
```

2022-05-23 02:54 UTC, danranVm commented on packages/cdk/scroll/src/virtual/composables/useScrollState.ts
> +  if (!virtual || dataLength === 0 || (!virtual && itemHeight * dataLength <= height)) {
```suggestion
  if (!virtual || dataLength === 0 || (itemHeight * dataLength <= height)) {
```
这个条件没任何意义啊，!virtual 在前面就判断了。

2022-05-23 02:54 UTC, danranVm commented on packages/cdk/scroll/src/virtual/contents/Holder.tsx
> -    const { handleWheel, handleTouchStart } = useEvents(holderRef, syncScrollTop, originScroll)
干掉这些原生事件确定没问题么，测试一下低版本的 chrome（79+）, 和火狐（72+）。

2022-05-23 02:54 UTC, danranVm commented on packages/cdk/scroll/src/virtual/composables/useScrollState.ts
> +  if (!virtual || dataLength === 0 || (!virtual && itemHeight * dataLength <= height)) {
```suggestion
  if (!virtual || dataLength === 0 || ( itemHeight * dataLength <= height)) {
```

这个判断没意义

2022-05-24 13:12 UTC, sallerli1 commented on packages/cdk/scroll/src/virtual/contents/Holder.tsx
> -    const { handleWheel, handleTouchStart } = useEvents(holderRef, syncScrollTop, originScroll)
测了chrome80和firefox72，没有问题

2022-09-13 02:56 UTC, merged