feat(comp: spin): add IxSpinProvider
IDuxFE/idux pull request #933
Opened 2022-05-28 12:18 UTC by liuzaijiang

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## What is the current behavior?

## What is the new behavior?

### IxSpinProvider

```props``` 保持和```spinProps```一致，但`spinning`默认为false

#### IxSpinProviderMethods

| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `open`   | 打开 | `(tip?: string, options?: SpinProviderFnOptions) => void` | `type SpinProviderFnOptions = Partial<SpinProviderProps>` |
| `close`  | 关闭 | `() => void` | - |

## Other information

2022-05-30 03:16 UTC, danranVm requested changes

2022-05-30 03:16 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +    let fnOptions = {}
```suggestion
    const spinOptions = ref<SpinOptions | undefined>()
```

2022-05-30 03:16 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +    const [tip, setTip] = useState(props.tip)
```suggestion
    const [spinning, setSpinning] = useState(props.spinning)
    watch(() => props.spinning, setSpinning)
    const [tip, setTip] = useState(props.tip)
    watch(() => props.tip, setTip)
```

2022-05-30 03:16 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +      fnOptions = reset
```suggestion
      setSpinning(true)
      setTip(tip) // 不要做非空判断，因为用户可能就是不需要 tip 提示
      spinOptions.value = options
```

2022-05-30 03:16 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +        tip: tip.value,
```suggestion
        ...props,
        ...spinOptions.value,
        spinning: spinning.value,
        tip: tip.value,
```

2022-05-30 12:34 UTC, liuzaijiang commented on packages/components/spin/src/SpinProvider.tsx
> +      const _options = isObject(tip) ? tip : options ?? {}
这里提供了两种使用方法：
```
1. open('text')
2. open({ spinProps })
```
兼容两种写法

2022-06-14 13:13 UTC, danranVm requested changes

2022-06-14 13:13 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +    const mergedPrefixCls = computed(() => `${common.prefixCls}-spin-provider`)
```suggestion
    const mergedPrefixCls = computed(() => `${common.prefixCls}-spin`)
```

2022-06-14 13:13 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +          `${mergedPrefixCls.value}-position`,
```suggestion
          `${mergedPrefixCls.value}-container`,
```

2022-06-14 13:13 UTC, danranVm commented on packages/components/spin/src/types.ts
> +  closeAll: () => void
```suggestion
export interface SpinRef {
   target: string | HTMLElement | (() => string | HTMLElement)
   update: (options?: options?: Omit<SpinOptions, 'target'>) => void
   update: (tip?: string, options?:  options?: Omit<SpinOptions, 'tip' | 'target'>) => void
   destroy: () => void
}


export interface SpinProviderRef {
  open: (options?: SpinOptions) => SpinRef
  open: (tip?: string, options?: Omit<SpinOptions, 'tip'>) => SpinRef
  update: (options?: SpinOptions) => void
  update: (tip?: string, options?:  options?: Omit<SpinOptions, 'tip'>) => void
  destroy: (target?: string | HTMLElement | (() => string | HTMLElement)) => void
  destroyAll: () => void
```

2022-06-14 13:13 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +    const spinContainersMap = reactive(new Map<HTMLElement, SpinContainerOptions>())
这里建议参考一下 modal, message 组件，用一个 ref 数组实现就好了，
target 就是作为 key 来使用，也不要把 convertTarget(target) 后的结果保存起来，每次要用的时候，在通过 target 去找就好了。

2022-06-14 13:13 UTC, danranVm commented on packages/components/spin/src/SpinProvider.tsx
> +    const spinContainersMap = reactive(new Map<HTMLElement, SpinContainerOptions>())
另外整个组件的实现代码还需要再优化一下。

2022-10-10 09:13 UTC, closed without merging