feat(comp:card): add selection state and disabled state
IDuxFE/idux pull request #983
Opened 2022-06-27 08:11 UTC by lionnnnn

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ x ] Tests for the changes have been added/updated or not needed
- [ x ] Docs and demo have been added/updated or not needed

## What is the current behavior?

1. card can not be selected or disabled.

## What is the new behavior?

1. card can selected or disabled.

## Other information

![image](https://user-images.githubusercontent.com/19869357/175892014-58de2bf1-1f02-4022-83bd-88c2767a2cf9.png)

![image](https://user-images.githubusercontent.com/19869357/175892039-c49e6f81-1541-48d2-a63a-aeb2a23c7a12.png)

![image](https://user-images.githubusercontent.com/19869357/175892065-36be943f-b69a-4d95-8f3e-4f6b1ba67438.png)

![image](https://user-images.githubusercontent.com/19869357/175892094-39c062b2-6fd7-4e2d-97ec-03c6333472f6.png)

2022-06-27 09:31 UTC, danranVm requested changes

2022-06-27 09:31 UTC, danranVm commented on packages/components/card/docs/Index.zh.md
> +| `onChange` | 选中状态发生变化后的回调  | `(selected: boolean) => void` | - | - | - | - |
```suggestion
| `selected` | 指定当前卡片是否选中  | `boolean` | `false` | - | - | - |
| `disabled` | 是否禁用当前卡片 | `boolean` | `false` | - | - | - |
| `onSelectedChange` | 选中状态发生变化后的回调  | `(selected: boolean) => void` | - | - | - | - |
```
selected 就不支持 v-model 了吧，感觉意义不大。
onChange => onSelectedChange

2022-06-27 09:31 UTC, danranVm commented on packages/components/card/src/Card.tsx
> +        [`${prefixCls}-selected`]: selectable && selected,
```suggestion
        [`${prefixCls}-selected`]: selectable && isSelected,
```

2022-06-27 09:31 UTC, danranVm commented on packages/components/card/src/Card.tsx
> +    }
```suggestion
   const [isSelected, setSelected ] = useState(props.selectable)
    const handleClick = () => {
      if (props.disabled || !iprops.selectable) {
        return
      }
      const newSelected = !isSelected.value
      setSelected(newSelected)
      callEmit(props.onSelectedChange, newSelected)
    }
```

card 不是表单组件，所以这里不应该用 useFormAccessor， 直接从 props 里拿值就好了

2022-06-27 10:28 UTC, lionnnnn commented on packages/components/card/docs/Index.zh.md
> +| `onChange` | 选中状态发生变化后的回调  | `(selected: boolean) => void` | - | - | - | - |
fixed

2022-06-27 10:28 UTC, lionnnnn commented on packages/components/card/src/Card.tsx
> +        [`${prefixCls}-selected`]: selectable && selected,
fixed

2022-06-27 11:19 UTC, danranVm requested changes

2022-06-27 11:19 UTC, danranVm commented on packages/components/card/src/Card.tsx
> +    const [selected, setSelected] = useControlledProp(props, 'selected', () => false)
```suggestion
    const [selected, setSelected] = useControlledProp(props, 'selected', false)
```

简单类型的初始值直接给就好了，引用类型的值，才需要用工厂函数。

2022-06-27 11:19 UTC, danranVm commented on packages/components/card/src/Card.tsx
> +    const isSelectable = computed(() => props.selectable ?? false)
```suggestion
    const isDisabled = computed(() => props.disabled)
    const isSelectable = computed(() => props.selectable)
```
因为这两个都有默认值，所以 ?? 没意义。

2022-06-27 11:19 UTC, danranVm commented on packages/components/card/src/Card.tsx
> +      callEmit(props.onSelectedChange, !selected.value)
```suggestion
      const newSelected = !selected.value
      setSelected(newSelected)
      callEmit(props.onSelectedChange, newSelected)
```
这里一定要用一个临时变量保存下，否则 setSelected 后，selected.value 的值就已经发生改变了。

2022-06-28 03:43 UTC, lionnnnn commented on packages/components/card/src/Card.tsx
> +    const [selected, setSelected] = useControlledProp(props, 'selected', () => false)
fixed

2022-06-28 03:43 UTC, lionnnnn commented on packages/components/card/src/Card.tsx
> +    const isSelectable = computed(() => props.selectable ?? false)
fixed

2022-06-28 03:55 UTC, danranVm approved these changes
LGTM.

2022-06-28 03:56 UTC, merged